import { createI18n } from '@chatoffice/i18n'

const zh = {
  title: '文件',
  close: '关闭文件面板',
  newFolder: '新建文件夹',
  newSubfolder: '新建子文件夹',
  untitledFolder: '未命名文件夹',
  open: '打开',
  rename: '重命名',
  revealInFolder: '打开所在文件夹',
  deleteFolder: '删除文件夹…',
  deleteFile: '删除文件…',
  deleteFolderConfirm: '「{name}」及其中的全部内容将移到回收站。',
  deleteFileConfirm: '「{name}」将移到回收站。',
  cancel: '取消',
  delete: '删除',
  moreActions: '{name} 更多操作',
  conflictTitle: '已存在同名项目',
  conflictBody: '目标文件夹里已有同名项目。要怎么处理？',
  conflictKeepBoth: '保留两者',
  conflictReplace: '替换',
  emptyFolder: '空文件夹',
  rootUnusable: '默认保存位置不可用。',
  failed: '操作失败',
}

const en = {
  title: 'Files',
  close: 'Close files pane',
  newFolder: 'New folder',
  newSubfolder: 'New subfolder',
  untitledFolder: 'Untitled folder',
  open: 'Open',
  rename: 'Rename',
  revealInFolder: 'Show in folder',
  deleteFolder: 'Delete folder…',
  deleteFile: 'Delete file…',
  deleteFolderConfirm: '"{name}" and everything inside it will be moved to the trash.',
  deleteFileConfirm: '"{name}" will be moved to the trash.',
  cancel: 'Cancel',
  delete: 'Delete',
  moreActions: 'More actions for {name}',
  conflictTitle: 'An item with that name already exists',
  conflictBody:
    'The target folder already contains an item with the same name. What would you like to do?',
  conflictKeepBoth: 'Keep both',
  conflictReplace: 'Replace',
  emptyFolder: 'Empty folder',
  rootUnusable: 'The default save location is unavailable.',
  failed: 'The operation failed',
} satisfies Record<keyof typeof zh, string>

const ja = {
  title: 'ファイル',
  close: 'ファイルパネルを閉じる',
  newFolder: '新しいフォルダー',
  newSubfolder: 'サブフォルダーを作成',
  untitledFolder: '名称未設定フォルダー',
  open: '開く',
  rename: '名前を変更',
  revealInFolder: 'フォルダーで表示',
  deleteFolder: 'フォルダーを削除…',
  deleteFile: 'ファイルを削除…',
  deleteFolderConfirm: '「{name}」とその中身はすべてゴミ箱に移動します。',
  deleteFileConfirm: '「{name}」をゴミ箱に移動します。',
  cancel: 'キャンセル',
  delete: '削除',
  moreActions: '{name} のその他の操作',
  conflictTitle: '同じ名前の項目があります',
  conflictBody: '移動先に同じ名前の項目があります。どうしますか？',
  conflictKeepBoth: '両方を残す',
  conflictReplace: '置き換える',
  emptyFolder: '空のフォルダー',
  rootUnusable: '既定の保存先が利用できません。',
  failed: '操作に失敗しました',
} satisfies Record<keyof typeof zh, string>

const ko = {
  title: '파일',
  close: '파일 패널 닫기',
  newFolder: '새 폴더',
  newSubfolder: '하위 폴더 만들기',
  untitledFolder: '제목 없는 폴더',
  open: '열기',
  rename: '이름 바꾸기',
  revealInFolder: '폴더에서 보기',
  deleteFolder: '폴더 삭제…',
  deleteFile: '파일 삭제…',
  deleteFolderConfirm: '"{name}" 폴더와 그 안의 모든 항목이 휴지통으로 이동합니다.',
  deleteFileConfirm: '"{name}"이(가) 휴지통으로 이동합니다.',
  cancel: '취소',
  delete: '삭제',
  moreActions: '{name} 추가 작업',
  conflictTitle: '같은 이름의 항목이 이미 있습니다',
  conflictBody: '대상 폴더에 같은 이름의 항목이 있습니다. 어떻게 할까요?',
  conflictKeepBoth: '둘 다 유지',
  conflictReplace: '바꾸기',
  emptyFolder: '빈 폴더',
  rootUnusable: '기본 저장 위치를 사용할 수 없습니다.',
  failed: '작업에 실패했습니다',
} satisfies Record<keyof typeof zh, string>

const fr = {
  title: 'Fichiers',
  close: 'Fermer le panneau des fichiers',
  newFolder: 'Nouveau dossier',
  newSubfolder: 'Nouveau sous-dossier',
  untitledFolder: 'Dossier sans titre',
  open: 'Ouvrir',
  rename: 'Renommer',
  revealInFolder: 'Afficher dans le dossier',
  deleteFolder: 'Supprimer le dossier…',
  deleteFile: 'Supprimer le fichier…',
  deleteFolderConfirm: '« {name} » et tout son contenu seront placés dans la corbeille.',
  deleteFileConfirm: '« {name} » sera placé dans la corbeille.',
  cancel: 'Annuler',
  delete: 'Supprimer',
  moreActions: 'Autres actions pour {name}',
  conflictTitle: 'Un élément du même nom existe déjà',
  conflictBody: 'Le dossier cible contient déjà un élément du même nom. Que souhaitez-vous faire ?',
  conflictKeepBoth: 'Conserver les deux',
  conflictReplace: 'Remplacer',
  emptyFolder: 'Dossier vide',
  rootUnusable: "L'emplacement d'enregistrement par défaut est indisponible.",
  failed: "L'opération a échoué",
} satisfies Record<keyof typeof zh, string>

const de = {
  title: 'Dateien',
  close: 'Dateibereich schließen',
  newFolder: 'Neuer Ordner',
  newSubfolder: 'Neuer Unterordner',
  untitledFolder: 'Unbenannter Ordner',
  open: 'Öffnen',
  rename: 'Umbenennen',
  revealInFolder: 'Im Ordner anzeigen',
  deleteFolder: 'Ordner löschen…',
  deleteFile: 'Datei löschen…',
  deleteFolderConfirm: '„{name}“ und der gesamte Inhalt werden in den Papierkorb verschoben.',
  deleteFileConfirm: '„{name}“ wird in den Papierkorb verschoben.',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  moreActions: 'Weitere Aktionen für {name}',
  conflictTitle: 'Ein Element mit diesem Namen existiert bereits',
  conflictBody:
    'Der Zielordner enthält bereits ein gleichnamiges Element. Wie möchten Sie fortfahren?',
  conflictKeepBoth: 'Beide behalten',
  conflictReplace: 'Ersetzen',
  emptyFolder: 'Leerer Ordner',
  rootUnusable: 'Der Standard-Speicherort ist nicht verfügbar.',
  failed: 'Der Vorgang ist fehlgeschlagen',
} satisfies Record<keyof typeof zh, string>

const es = {
  title: 'Archivos',
  close: 'Cerrar el panel de archivos',
  newFolder: 'Nueva carpeta',
  newSubfolder: 'Nueva subcarpeta',
  untitledFolder: 'Carpeta sin título',
  open: 'Abrir',
  rename: 'Cambiar nombre',
  revealInFolder: 'Mostrar en la carpeta',
  deleteFolder: 'Eliminar carpeta…',
  deleteFile: 'Eliminar archivo…',
  deleteFolderConfirm: '«{name}» y todo su contenido se moverán a la papelera.',
  deleteFileConfirm: '«{name}» se moverá a la papelera.',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  moreActions: 'Más acciones para {name}',
  conflictTitle: 'Ya existe un elemento con ese nombre',
  conflictBody:
    'La carpeta de destino ya contiene un elemento con el mismo nombre. ¿Qué quieres hacer?',
  conflictKeepBoth: 'Conservar ambos',
  conflictReplace: 'Reemplazar',
  emptyFolder: 'Carpeta vacía',
  rootUnusable: 'La ubicación de guardado predeterminada no está disponible.',
  failed: 'La operación falló',
} satisfies Record<keyof typeof zh, string>

const th = {
  title: 'ไฟล์',
  close: 'ปิดแผงไฟล์',
  newFolder: 'โฟลเดอร์ใหม่',
  newSubfolder: 'สร้างโฟลเดอร์ย่อย',
  untitledFolder: 'โฟลเดอร์ไม่มีชื่อ',
  open: 'เปิด',
  rename: 'เปลี่ยนชื่อ',
  revealInFolder: 'แสดงในโฟลเดอร์',
  deleteFolder: 'ลบโฟลเดอร์…',
  deleteFile: 'ลบไฟล์…',
  deleteFolderConfirm: '"{name}" และทุกอย่างภายในจะถูกย้ายไปถังขยะ',
  deleteFileConfirm: '"{name}" จะถูกย้ายไปถังขยะ',
  cancel: 'ยกเลิก',
  delete: 'ลบ',
  moreActions: 'การดำเนินการเพิ่มเติมสำหรับ {name}',
  conflictTitle: 'มีรายการชื่อเดียวกันอยู่แล้ว',
  conflictBody: 'โฟลเดอร์ปลายทางมีรายการชื่อเดียวกันอยู่แล้ว ต้องการทำอย่างไร',
  conflictKeepBoth: 'เก็บทั้งคู่',
  conflictReplace: 'แทนที่',
  emptyFolder: 'โฟลเดอร์ว่าง',
  rootUnusable: 'ตำแหน่งบันทึกเริ่มต้นใช้งานไม่ได้',
  failed: 'การดำเนินการล้มเหลว',
} satisfies Record<keyof typeof zh, string>

const id = {
  title: 'File',
  close: 'Tutup panel file',
  newFolder: 'Folder baru',
  newSubfolder: 'Subfolder baru',
  untitledFolder: 'Folder tanpa judul',
  open: 'Buka',
  rename: 'Ubah nama',
  revealInFolder: 'Tampilkan di folder',
  deleteFolder: 'Hapus folder…',
  deleteFile: 'Hapus file…',
  deleteFolderConfirm: '"{name}" beserta seluruh isinya akan dipindahkan ke tempat sampah.',
  deleteFileConfirm: '"{name}" akan dipindahkan ke tempat sampah.',
  cancel: 'Batal',
  delete: 'Hapus',
  moreActions: 'Tindakan lainnya untuk {name}',
  conflictTitle: 'Item dengan nama itu sudah ada',
  conflictBody:
    'Folder tujuan sudah berisi item dengan nama yang sama. Apa yang ingin Anda lakukan?',
  conflictKeepBoth: 'Simpan keduanya',
  conflictReplace: 'Ganti',
  emptyFolder: 'Folder kosong',
  rootUnusable: 'Lokasi penyimpanan default tidak tersedia.',
  failed: 'Operasi gagal',
} satisfies Record<keyof typeof zh, string>

const ru = {
  title: 'Файлы',
  close: 'Закрыть панель файлов',
  newFolder: 'Новая папка',
  newSubfolder: 'Новая подпапка',
  untitledFolder: 'Папка без названия',
  open: 'Открыть',
  rename: 'Переименовать',
  revealInFolder: 'Показать в папке',
  deleteFolder: 'Удалить папку…',
  deleteFile: 'Удалить файл…',
  deleteFolderConfirm: '«{name}» и всё её содержимое будут перемещены в корзину.',
  deleteFileConfirm: '«{name}» будет перемещён в корзину.',
  cancel: 'Отмена',
  delete: 'Удалить',
  moreActions: 'Другие действия для {name}',
  conflictTitle: 'Элемент с таким именем уже существует',
  conflictBody: 'В целевой папке уже есть элемент с таким именем. Что сделать?',
  conflictKeepBoth: 'Оставить оба',
  conflictReplace: 'Заменить',
  emptyFolder: 'Пустая папка',
  rootUnusable: 'Папка сохранения по умолчанию недоступна.',
  failed: 'Не удалось выполнить операцию',
} satisfies Record<keyof typeof zh, string>

const ar = {
  title: 'الملفات',
  close: 'إغلاق لوحة الملفات',
  newFolder: 'مجلد جديد',
  newSubfolder: 'مجلد فرعي جديد',
  untitledFolder: 'مجلد بدون اسم',
  open: 'فتح',
  rename: 'إعادة تسمية',
  revealInFolder: 'إظهار في المجلد',
  deleteFolder: 'حذف المجلد…',
  deleteFile: 'حذف الملف…',
  deleteFolderConfirm: 'سيتم نقل "{name}" وكل ما بداخله إلى سلة المهملات.',
  deleteFileConfirm: 'سيتم نقل "{name}" إلى سلة المهملات.',
  cancel: 'إلغاء',
  delete: 'حذف',
  moreActions: 'إجراءات إضافية لـ {name}',
  conflictTitle: 'يوجد عنصر بهذا الاسم بالفعل',
  conflictBody: 'يحتوي المجلد الهدف بالفعل على عنصر بالاسم نفسه. ماذا تريد أن تفعل؟',
  conflictKeepBoth: 'الاحتفاظ بكليهما',
  conflictReplace: 'استبدال',
  emptyFolder: 'مجلد فارغ',
  rootUnusable: 'موقع الحفظ الافتراضي غير متاح.',
  failed: 'فشلت العملية',
} satisfies Record<keyof typeof zh, string>

const pt = {
  title: 'Arquivos',
  close: 'Fechar o painel de arquivos',
  newFolder: 'Nova pasta',
  newSubfolder: 'Nova subpasta',
  untitledFolder: 'Pasta sem título',
  open: 'Abrir',
  rename: 'Renomear',
  revealInFolder: 'Mostrar na pasta',
  deleteFolder: 'Excluir pasta…',
  deleteFile: 'Excluir arquivo…',
  deleteFolderConfirm: '"{name}" e todo o seu conteúdo serão movidos para a lixeira.',
  deleteFileConfirm: '"{name}" será movido para a lixeira.',
  cancel: 'Cancelar',
  delete: 'Excluir',
  moreActions: 'Mais ações para {name}',
  conflictTitle: 'Já existe um item com esse nome',
  conflictBody: 'A pasta de destino já contém um item com o mesmo nome. O que deseja fazer?',
  conflictKeepBoth: 'Manter ambos',
  conflictReplace: 'Substituir',
  emptyFolder: 'Pasta vazia',
  rootUnusable: 'O local de salvamento padrão está indisponível.',
  failed: 'A operação falhou',
} satisfies Record<keyof typeof zh, string>

const it = {
  title: 'File',
  close: 'Chiudi il pannello dei file',
  newFolder: 'Nuova cartella',
  newSubfolder: 'Nuova sottocartella',
  untitledFolder: 'Cartella senza titolo',
  open: 'Apri',
  rename: 'Rinomina',
  revealInFolder: 'Mostra nella cartella',
  deleteFolder: 'Elimina cartella…',
  deleteFile: 'Elimina file…',
  deleteFolderConfirm: '"{name}" e tutto il suo contenuto verranno spostati nel cestino.',
  deleteFileConfirm: '"{name}" verrà spostato nel cestino.',
  cancel: 'Annulla',
  delete: 'Elimina',
  moreActions: 'Altre azioni per {name}',
  conflictTitle: 'Esiste già un elemento con questo nome',
  conflictBody:
    'La cartella di destinazione contiene già un elemento con lo stesso nome. Cosa vuoi fare?',
  conflictKeepBoth: 'Mantieni entrambi',
  conflictReplace: 'Sostituisci',
  emptyFolder: 'Cartella vuota',
  rootUnusable: 'La posizione di salvataggio predefinita non è disponibile.',
  failed: 'Operazione non riuscita',
} satisfies Record<keyof typeof zh, string>

const pl = {
  title: 'Pliki',
  close: 'Zamknij panel plików',
  newFolder: 'Nowy folder',
  newSubfolder: 'Nowy podfolder',
  untitledFolder: 'Folder bez nazwy',
  open: 'Otwórz',
  rename: 'Zmień nazwę',
  revealInFolder: 'Pokaż w folderze',
  deleteFolder: 'Usuń folder…',
  deleteFile: 'Usuń plik…',
  deleteFolderConfirm: '„{name}” i cała jego zawartość zostaną przeniesione do kosza.',
  deleteFileConfirm: '„{name}” zostanie przeniesiony do kosza.',
  cancel: 'Anuluj',
  delete: 'Usuń',
  moreActions: 'Więcej działań dla {name}',
  conflictTitle: 'Element o tej nazwie już istnieje',
  conflictBody: 'Folder docelowy już zawiera element o tej nazwie. Co chcesz zrobić?',
  conflictKeepBoth: 'Zachowaj oba',
  conflictReplace: 'Zastąp',
  emptyFolder: 'Pusty folder',
  rootUnusable: 'Domyślna lokalizacja zapisu jest niedostępna.',
  failed: 'Operacja nie powiodła się',
} satisfies Record<keyof typeof zh, string>

const cs = {
  title: 'Soubory',
  close: 'Zavřít panel souborů',
  newFolder: 'Nová složka',
  newSubfolder: 'Nová podsložka',
  untitledFolder: 'Složka bez názvu',
  open: 'Otevřít',
  rename: 'Přejmenovat',
  revealInFolder: 'Zobrazit ve složce',
  deleteFolder: 'Smazat složku…',
  deleteFile: 'Smazat soubor…',
  deleteFolderConfirm: '„{name}“ a celý její obsah budou přesunuty do koše.',
  deleteFileConfirm: '„{name}“ bude přesunut do koše.',
  cancel: 'Zrušit',
  delete: 'Smazat',
  moreActions: 'Další akce pro {name}',
  conflictTitle: 'Položka s tímto názvem již existuje',
  conflictBody: 'Cílová složka již obsahuje položku se stejným názvem. Co chcete udělat?',
  conflictKeepBoth: 'Zachovat obě',
  conflictReplace: 'Nahradit',
  emptyFolder: 'Prázdná složka',
  rootUnusable: 'Výchozí umístění pro ukládání není dostupné.',
  failed: 'Operace se nezdařila',
} satisfies Record<keyof typeof zh, string>

const nl = {
  title: 'Bestanden',
  close: 'Bestandenpaneel sluiten',
  newFolder: 'Nieuwe map',
  newSubfolder: 'Nieuwe submap',
  untitledFolder: 'Naamloze map',
  open: 'Openen',
  rename: 'Naam wijzigen',
  revealInFolder: 'Tonen in map',
  deleteFolder: 'Map verwijderen…',
  deleteFile: 'Bestand verwijderen…',
  deleteFolderConfirm: '"{name}" en alles erin worden naar de prullenbak verplaatst.',
  deleteFileConfirm: '"{name}" wordt naar de prullenbak verplaatst.',
  cancel: 'Annuleren',
  delete: 'Verwijderen',
  moreActions: 'Meer acties voor {name}',
  conflictTitle: 'Er bestaat al een item met die naam',
  conflictBody: 'De doelmap bevat al een item met dezelfde naam. Wat wilt u doen?',
  conflictKeepBoth: 'Beide behouden',
  conflictReplace: 'Vervangen',
  emptyFolder: 'Lege map',
  rootUnusable: 'De standaard opslaglocatie is niet beschikbaar.',
  failed: 'De bewerking is mislukt',
} satisfies Record<keyof typeof zh, string>

const ms = {
  title: 'Fail',
  close: 'Tutup panel fail',
  newFolder: 'Folder baharu',
  newSubfolder: 'Subfolder baharu',
  untitledFolder: 'Folder tanpa tajuk',
  open: 'Buka',
  rename: 'Namakan semula',
  revealInFolder: 'Tunjukkan dalam folder',
  deleteFolder: 'Padam folder…',
  deleteFile: 'Padam fail…',
  deleteFolderConfirm: '"{name}" dan semua isinya akan dipindahkan ke tong sampah.',
  deleteFileConfirm: '"{name}" akan dipindahkan ke tong sampah.',
  cancel: 'Batal',
  delete: 'Padam',
  moreActions: 'Tindakan lanjut untuk {name}',
  conflictTitle: 'Item dengan nama itu sudah wujud',
  conflictBody:
    'Folder sasaran sudah mengandungi item dengan nama yang sama. Apa yang anda mahu lakukan?',
  conflictKeepBoth: 'Simpan kedua-duanya',
  conflictReplace: 'Ganti',
  emptyFolder: 'Folder kosong',
  rootUnusable: 'Lokasi simpan lalai tidak tersedia.',
  failed: 'Operasi gagal',
} satisfies Record<keyof typeof zh, string>

const he = {
  title: 'קבצים',
  close: 'סגירת חלונית הקבצים',
  newFolder: 'תיקייה חדשה',
  newSubfolder: 'תת-תיקייה חדשה',
  untitledFolder: 'תיקייה ללא שם',
  open: 'פתיחה',
  rename: 'שינוי שם',
  revealInFolder: 'הצגה בתיקייה',
  deleteFolder: 'מחיקת תיקייה…',
  deleteFile: 'מחיקת קובץ…',
  deleteFolderConfirm: '"{name}" וכל תוכנה יועברו לסל המחזור.',
  deleteFileConfirm: '"{name}" יועבר לסל המחזור.',
  cancel: 'ביטול',
  delete: 'מחיקה',
  moreActions: 'פעולות נוספות עבור {name}',
  conflictTitle: 'פריט בשם זה כבר קיים',
  conflictBody: 'תיקיית היעד כבר מכילה פריט באותו שם. מה לעשות?',
  conflictKeepBoth: 'לשמור את שניהם',
  conflictReplace: 'להחליף',
  emptyFolder: 'תיקייה ריקה',
  rootUnusable: 'מיקום השמירה המוגדר כברירת מחדל אינו זמין.',
  failed: 'הפעולה נכשלה',
} satisfies Record<keyof typeof zh, string>

const hi = {
  title: 'फ़ाइलें',
  close: 'फ़ाइल पैनल बंद करें',
  newFolder: 'नया फ़ोल्डर',
  newSubfolder: 'नया सब-फ़ोल्डर',
  untitledFolder: 'बिना नाम का फ़ोल्डर',
  open: 'खोलें',
  rename: 'नाम बदलें',
  revealInFolder: 'फ़ोल्डर में दिखाएँ',
  deleteFolder: 'फ़ोल्डर हटाएँ…',
  deleteFile: 'फ़ाइल हटाएँ…',
  deleteFolderConfirm: '"{name}" और उसके अंदर की सभी चीज़ें ट्रैश में चली जाएँगी।',
  deleteFileConfirm: '"{name}" ट्रैश में चली जाएगी।',
  cancel: 'रद्द करें',
  delete: 'हटाएँ',
  moreActions: '{name} के लिए और कार्रवाइयाँ',
  conflictTitle: 'इस नाम का आइटम पहले से मौजूद है',
  conflictBody: 'लक्ष्य फ़ोल्डर में पहले से इसी नाम का आइटम है। आप क्या करना चाहेंगे?',
  conflictKeepBoth: 'दोनों रखें',
  conflictReplace: 'बदलें',
  emptyFolder: 'खाली फ़ोल्डर',
  rootUnusable: 'डिफ़ॉल्ट सेव स्थान उपलब्ध नहीं है।',
  failed: 'कार्रवाई विफल रही',
} satisfies Record<keyof typeof zh, string>

const zhTW = {
  title: '檔案',
  close: '關閉檔案面板',
  newFolder: '新增資料夾',
  newSubfolder: '新增子資料夾',
  untitledFolder: '未命名資料夾',
  open: '開啟',
  rename: '重新命名',
  revealInFolder: '在資料夾中顯示',
  deleteFolder: '刪除資料夾…',
  deleteFile: '刪除檔案…',
  deleteFolderConfirm: '「{name}」及其中的全部內容將移到垃圾桶。',
  deleteFileConfirm: '「{name}」將移到垃圾桶。',
  cancel: '取消',
  delete: '刪除',
  moreActions: '{name} 更多動作',
  conflictTitle: '已有同名項目',
  conflictBody: '目標資料夾中已有同名項目。要如何處理？',
  conflictKeepBoth: '保留兩者',
  conflictReplace: '取代',
  emptyFolder: '空資料夾',
  rootUnusable: '預設儲存位置無法使用。',
  failed: '操作失敗',
} satisfies Record<keyof typeof zh, string>

export const tFilesPane = createI18n({
  zh,
  en,
  ja,
  ko,
  fr,
  de,
  es,
  th,
  id,
  ru,
  ar,
  pt,
  it,
  pl,
  cs,
  nl,
  ms,
  he,
  hi,
  'zh-TW': zhTW,
})

export type FilesPaneStringKey = keyof typeof zh

/** the pane's title ("Files"), also used by the apps for their toggle button and edge tab */
export function filesPaneTitle(lang: Parameters<typeof tFilesPane>[0]): string {
  return tFilesPane(lang, 'title')
}
