/**
 * InsertImageDialog strings — zh source of truth, en fallback; other locales
 * fall back to en (same policy as ModelSettingsPage). Kept in-module so the
 * shared dialog needs no per-app i18n wiring.
 */
export type InsertImageLang = 'zh' | 'en'

const zh = {
  title: '插入媒体',
  tabLocal: '本地文件',
  tabWeb: '网络图片',
  tabAI: 'AI 生成',
  close: '关闭',
  pickLocal: '选择本地图片',
  localHint: '支持 PNG / JPEG / GIF / WebP / BMP，20MB 以内',
  searchPlaceholder: '输入关键词搜索图片…',
  search: '搜索',
  sourceWeb: '网页',
  sourcePexels: 'Pexels',
  sourcePixabay: 'Pixabay',
  sourceUnsplash: 'Unsplash',
  sourceSerper: 'Serper',
  sourceTavily: 'Tavily',
  sourceLinkup: 'Linkup',
  sourceSearxng: 'SearxNG',
  sourceDuckDuckGo: 'DuckDuckGo',
  sourceBing: 'Bing',
  sourceNoImageSearch: '该平台不支持图片搜索',
  sourceKeyMissing: '未配置 Key（点击 ⚙ 配置）',
  keysTitleUnsplash: 'Unsplash Access Key',
  keysHintUnsplash: 'Unsplash 图库需要免费 Access Key；',
  unsplashKey: 'Unsplash Access Key',
  keysTitlePexels: 'Pexels API Key',
  keysTitlePixabay: 'Pixabay API Key',
  keysHintPexels: 'Pexels 图库需要免费 API Key；',
  keysHintPixabay: 'Pixabay 图库需要免费 API Key；',
  keysApply: '申请后粘贴到此处即可使用',
  pexelsKey: 'Pexels Key',
  pixabayKey: 'Pixabay Key',
  keyPlaceholder: '未配置（粘贴 Key）',
  keysSave: '保存',
  keysSaved: '已保存',
  keyApplyUrl: '去申请 Key ↗',
  keyTest: '测试连接',
  keyTesting: '测试中…',
  keyTestOk: '连接成功',
  keyTestFail: '连接失败',
  emptyQuery: '输入关键词开始搜索',
  noResults: '没有找到图片，换个关键词试试',
  loadMore: '下一批',
  loadingMore: '加载中…',
  noMoreImages: '已经到底了',
  diagTitle: '各搜索源状态：',
  diagOk: '命中',
  diagError: '失败',
  diagSkipped: '未配置',
  insert: '插入',
  aiPrompt: '描述你想要的图片…',
  aiGenerate: '生成图像',
  aiGenerating: '生成中…',
  aiModelLabel: '模型',
  aiModelGroup: '图像生成',
  aiModelManage: '打开模型设置…',
  aiNoModels: '未配置生图模型：请在模型设置中启用生图模型，或登录后使用默认生图',
  aiOpenModelSettings: '打开模型设置',
  aiErrorTitle: '生成失败',
  loadFail: '图片下载失败，请重试',
  aiModelGroupVideo: '视频生成',
  aiKindImage: 'AI 生图',
  aiKindVideo: 'AI 生视频',
  aiKindSvg: 'SVG 生成',
  aiNoVideoModels: '未配置视频模型：请在模型设置中启用生视频模型',
  aiSvgPrompt: '描述你想要的矢量插画…',
  aiSvgNoModels: '未选择 SVG 模型：在设置 → 生图、媒体与搜索 中选择默认对话模型',
  aiSvgRasterFail: 'SVG 渲染失败：{message}',
  aiSvgGen: '生成 SVG',
  videoSubmit: '提交生成任务',
  videoSubmitting: '提交中…',
  videoBusyLimit: '视频任务并发已达上限（3 个），请等待任务完成后再试',
  videoTasksTitle: '视频任务（关闭窗口后仍在后台生成）',
  videoStatusQueued: '排队中',
  videoStatusRunning: '生成中',
  videoStatusSucceeded: '已完成',
  videoStatusFailed: '失败',
  videoStatusCancelled: '已取消',
  videoCancel: '取消任务',
  videoRetry: '重试',
  videoPreviewLoading: '正在加载预览…',
  videoHostHintSlides: '视频完成后将嵌入当前幻灯片，可在放映时播放',
  videoHostHintDocs: '文档暂不支持嵌入视频：将插入封面帧图片并附视频链接',
  videoHostHintSheets: '表格不支持插入视频，仅幻灯片可嵌入、文档将插入封面帧链接',
  videoSheetsInsertRefused: '表格不支持插入视频：请改在幻灯片中嵌入，或改用文档插入封面帧链接',
}

const en: typeof zh = {
  title: 'Insert Media',
  tabLocal: 'Local File',
  tabWeb: 'Web Images',
  tabAI: 'AI Generate',
  close: 'Close',
  pickLocal: 'Choose a local image',
  localHint: 'PNG / JPEG / GIF / WebP / BMP up to 20MB',
  searchPlaceholder: 'Search images by keyword…',
  search: 'Search',
  sourceWeb: 'Web',
  sourcePexels: 'Pexels',
  sourcePixabay: 'Pixabay',
  sourceUnsplash: 'Unsplash',
  sourceSerper: 'Serper',
  sourceTavily: 'Tavily',
  sourceLinkup: 'Linkup',
  sourceSearxng: 'SearxNG',
  sourceDuckDuckGo: 'DuckDuckGo',
  sourceBing: 'Bing',
  sourceNoImageSearch: 'This platform cannot search images',
  sourceKeyMissing: 'Key not configured (click ⚙ to configure)',
  keysTitleUnsplash: 'Unsplash Access Key',
  keysHintUnsplash: 'Unsplash needs a free Access Key.',
  unsplashKey: 'Unsplash Access Key',
  keysTitlePexels: 'Pexels API Key',
  keysTitlePixabay: 'Pixabay API Key',
  keysHintPexels: 'Pexels needs a free API key.',
  keysHintPixabay: 'Pixabay needs a free API key.',
  keysApply: 'Paste the key here once granted.',
  pexelsKey: 'Pexels Key',
  pixabayKey: 'Pixabay Key',
  keyPlaceholder: 'Not configured (paste key)',
  keysSave: 'Save',
  keysSaved: 'Saved',
  keyApplyUrl: 'Get a key ↗',
  keyTest: 'Test connection',
  keyTesting: 'Testing…',
  keyTestOk: 'Connected',
  keyTestFail: 'Connection failed',
  emptyQuery: 'Type a keyword to start searching',
  noResults: 'No images found — try another keyword',
  loadMore: 'Next batch',
  loadingMore: 'Loading…',
  noMoreImages: 'No more images',
  diagTitle: 'Backend status:',
  diagOk: 'hits',
  diagError: 'failed',
  diagSkipped: 'not configured',
  insert: 'Insert',
  aiPrompt: 'Describe the image you want…',
  aiGenerate: 'Generate',
  aiGenerating: 'Generating…',
  aiModelLabel: 'Model',
  aiModelGroup: 'Image generation',
  aiModelManage: 'Open Model Settings…',
  aiNoModels:
    'No image model configured: enable one in Model Settings, or sign in to use the default.',
  aiOpenModelSettings: 'Open Model Settings',
  aiErrorTitle: 'Generation failed',
  loadFail: 'Image download failed, please retry',
  aiModelGroupVideo: 'Video generation',
  videoSubmit: 'Submit generation task',
  videoSubmitting: 'Submitting…',
  videoBusyLimit: 'Video task concurrency limit reached (3) — wait for a task to finish first',
  videoTasksTitle: 'Video tasks (generation continues after this dialog closes)',
  videoStatusQueued: 'Queued',
  videoStatusRunning: 'Generating',
  videoStatusSucceeded: 'Done',
  videoStatusFailed: 'Failed',
  videoStatusCancelled: 'Cancelled',
  videoCancel: 'Cancel task',
  videoRetry: 'Retry',
  videoPreviewLoading: 'Loading preview…',
  videoHostHintSlides: 'When done, the video is embedded in the slide and plays in presentations',
  videoHostHintDocs:
    'Documents cannot embed video yet: a cover-frame image plus a video link is inserted instead',
  videoHostHintSheets:
    'Spreadsheets cannot embed video: slides embed it, documents insert a cover frame + link',
  videoSheetsInsertRefused:
    'Spreadsheets do not support video insertion: embed in slides, or use documents for a cover frame + link',
  aiKindImage: 'AI Image',
  aiKindVideo: 'AI Video',
  aiKindSvg: 'SVG',
  aiNoVideoModels: 'No video model configured: enable one in Model Settings.',
  aiSvgPrompt: 'Describe the vector illustration you want…',
  aiSvgNoModels: 'No SVG model picked: choose a default chat model in Settings → AI Media & Search',
  aiSvgRasterFail: 'SVG render failed: {message}',
  aiSvgGen: 'Generate SVG',
}

export function insertImageStrings(lang?: string): typeof zh {
  const tag = (lang ?? (typeof document !== 'undefined' ? document.documentElement.lang : 'zh'))
    .toLowerCase()
    .startsWith('zh')
    ? 'zh'
    : 'en'
  return tag === 'zh' ? zh : en
}
