/**
 * Shape animation (<p:timing>) read/write — the engine layer behind PowerPoint's
 * "Animations" tab.
 *
 * Model: a slide's animations are an ordered list SlideAnimation[], each item =
 * target shape (spid) + effect + trigger (onClick/withPrev/afterPrev) +
 * duration/delay. On write-back the whole <p:timing> is rebuilt (tmRoot → mainSeq
 * → one par per "click group" → one par per effect), structurally identical to
 * the skeleton PowerPoint itself generates, so the saved pptx plays directly in
 * PowerPoint.
 *
 * spid targeting: OOXML animations use <p:spTgt spid="N"/> pointing at the shape's
 * <p:cNvPr id="N">. The editor's element ids are transient (they change on
 * reparse), so elementSpid() extracts the stable cNvPr id from the element's raw
 * bytes for the mapping.
 *
 * Read-back: parsing our own generated skeleton round-trips losslessly; complex
 * timings generated by PowerPoint get a best-effort downgrade (unmodeled presetIDs
 * map to a similar effect in the same class).
 */
import type { Slide, SlideElement } from './types'

export type AnimEffectKind =
  // Entrance
  | 'appear'
  | 'fade'
  | 'flyIn'
  | 'wipe'
  | 'wipeDown'
  | 'splitIn'
  | 'bounce'
  | 'flipIn'
  | 'zoom'
  // Entrance — classic animEffect filter families (WPS gallery parity, first batch)
  | 'blinds'
  | 'box'
  | 'checkerboard'
  | 'circleIn'
  | 'crawlIn'
  | 'diamond'
  | 'dissolveIn'
  | 'randomBars'
  | 'stretch'
  | 'strips'
  | 'wedge'
  | 'wheel'
  | 'swivel'
  | 'peekIn'
  // Emphasis
  | 'pulse'
  | 'spin'
  | 'grow'
  | 'teeter'
  // Exit
  | 'disappear'
  | 'fadeOut'
  | 'flyOut'
  | 'wipeOut'
  | 'shrink'
  | 'zoomOut'
  // Exit — filter-family mirrors
  | 'boxOut'
  | 'checkerboardOut'
  | 'dissolveOut'
  | 'randomBarsOut'
  // Motion path (move along a path)
  | 'motionPath'

export type AnimTrigger = 'onClick' | 'withPrev' | 'afterPrev'
/** Side a fly/wipe effect comes from (entrance) or leaves towards (exit). */
export type AnimDirection = 'top' | 'bottom' | 'left' | 'right'
export const ANIM_DIRECTIONS: readonly AnimDirection[] = ['top', 'bottom', 'left', 'right']

export const ANIM_TRIGGERS: readonly AnimTrigger[] = ['onClick', 'withPrev', 'afterPrev']
export type AnimClass = 'entrance' | 'emphasis' | 'exit' | 'path'

/** Each filter kind's OOXML filter string (entrance direction), variant-aware. */
const ENTRANCE_FILTERS: Record<string, string> = {
  blinds: 'blinds(horizontal)',
  box: 'box(in)',
  checkerboard: 'checkerboard(across)',
  circleIn: 'circle(out)',
  diamond: 'diamond(in)',
  dissolveIn: 'dissolve',
  randomBars: 'randombar(horizontal)',
  strips: 'strips(downRight)',
  wedge: 'wedge',
  wheel: 'wheel(1)',
}

/** Per-effect variant → filter argument + presetSubtype (效果选项表). */
export const ANIM_VARIANTS: Partial<
  Record<AnimEffectKind, ReadonlyArray<{ value: string; sub: number }>>
> = {
  blinds: [
    { value: 'horizontal', sub: 1 },
    { value: 'vertical', sub: 2 },
  ],
  randomBars: [
    { value: 'horizontal', sub: 1 },
    { value: 'vertical', sub: 2 },
  ],
  randomBarsOut: [
    { value: 'horizontal', sub: 1 },
    { value: 'vertical', sub: 2 },
  ],
  strips: [
    { value: 'downRight', sub: 21 },
    { value: 'downLeft', sub: 22 },
    { value: 'upRight', sub: 23 },
    { value: 'upLeft', sub: 24 },
  ],
  wheel: [
    { value: '1', sub: 1 },
    { value: '2', sub: 2 },
    { value: '3', sub: 3 },
    { value: '4', sub: 4 },
    { value: '8', sub: 8 },
  ],
  box: [
    { value: 'in', sub: 16 },
    { value: 'out', sub: 524 },
  ],
  boxOut: [
    { value: 'in', sub: 16 },
    { value: 'out', sub: 524 },
  ],
  circleIn: [
    { value: 'out', sub: 524 },
    { value: 'in', sub: 16 },
  ],
  crawlIn: [
    { value: 'left', sub: 8 },
    { value: 'right', sub: 2 },
    { value: 'top', sub: 4 },
    { value: 'bottom', sub: 1 },
  ],
}

/** filter string of an effect+variant (PowerPoint plays this verbatim). */
function animEffectFilter(effect: AnimEffectKind, variant: string | undefined): string {
  const base = ENTRANCE_FILTERS[effect]
  if (!base) return 'fade'
  const v = variant && ANIM_VARIANTS[effect]?.some((x) => x.value === variant) ? variant : undefined
  if (!v) return base
  const open = base.indexOf('(')
  if (open < 0) return base
  return base.slice(0, open + 1) + v + ')'
}

/** presetSubtype of an effect+variant (animation-pane label metadata). */
export function animVariantSubtype(effect: AnimEffectKind, variant: string | undefined): number {
  if (!variant) return 0
  return ANIM_VARIANTS[effect]?.find((x) => x.value === variant)?.sub ?? 0
}

/** Read the variant back out of a filter string (效果选项 echo). */
export function animVariantFromFilter(effect: AnimEffectKind, filter: string): string | undefined {
  const arg = /\(([^)]*)\)/.exec(filter)?.[1]
  if (!arg) return undefined
  return ANIM_VARIANTS[effect]?.find((x) => x.value === arg)?.value
}

export interface SlideAnimation {
  /** Target shape's cNvPr id (<p:spTgt spid>) */
  spid: number
  effect: AnimEffectKind
  trigger: AnimTrigger
  durationMs: number
  delayMs: number
  /**
   * Motion path (valid when effect='motionPath'): SVG subset M/L/C/Z,
   * coordinates 0..1 relative to slide width/height (same as OOXML animMotion's
   * relative path).
   */
  motionPath?: string
  /** Per-paragraph animation: 0-based paragraph number (written as pgRg st/end); unset = whole shape */
  paragraph?: number
  /**
   * 效果选项/变体 (PowerPoint 效果选项): blinds/randomBars 'horizontal'|'vertical',
   * strips 'downRight'|'downLeft'|'upRight'|'upLeft', wheel '1'|'2'|'3'|'4'|'8'
   * (spokes), box 'in'|'out', circleIn 'in'|'out', crawlIn edge. PowerPoint plays
   * the animEffect filter string, so the variant is encoded there; presetSubtype
   * mirrors it for the animation pane label.
   */
  variant?: string
  /**
   * 播完动画后快退 (WPS 动画属性): afterLast="1" on the effect cTn — the shape
   * returns to its invisible state after the effect finishes (entrance/exit
   * semantics vary in WPS; we mirror PowerPoint's rewind flag verbatim).
   */
  rewind?: boolean
  /** flyIn/flyOut/wipe/wipeOut only; unset = the effect's PowerPoint default side (bottom) */
  direction?: AnimDirection
  /**
   * Verbatim effect <p:par> for presets the model has no writer for: read-back keeps
   * the original bytes here (effect holds the closest modeled approximation) and the
   * writer emits them unchanged, so editing another animation never downgrades this one.
   */
  presetXml?: string
  /** presetID/presetClass/presetSubtype of a kept-verbatim effect (read-back, with presetXml) */
  preset?: { id: number; cls: string; sub: number }
}

/** Effect → class (entrance/emphasis/exit/motion path). */
export function animClassOf(effect: AnimEffectKind): AnimClass {
  switch (effect) {
    case 'appear':
    case 'fade':
    case 'flyIn':
    case 'wipe':
    case 'wipeDown':
    case 'splitIn':
    case 'bounce':
    case 'flipIn':
    case 'zoom':
    case 'blinds':
    case 'box':
    case 'checkerboard':
    case 'circleIn':
    case 'crawlIn':
    case 'diamond':
    case 'dissolveIn':
    case 'randomBars':
    case 'stretch':
    case 'strips':
    case 'wedge':
    case 'wheel':
    case 'swivel':
    case 'peekIn':
      return 'entrance'
    case 'pulse':
    case 'spin':
    case 'grow':
    case 'teeter':
      return 'emphasis'
    case 'motionPath':
      return 'path'
    default:
      return 'exit'
  }
}

/** Extract the element's own <p:cNvPr id> from its raw bytes (the first one is the element itself; group children follow). */
export function elementSpid(el: SlideElement): number | null {
  const m = /<p:cNvPr\s[^>]*\bid="(\d+)"/.exec(el.anchor.originalXml)
  return m ? Number(m[1]) : null
}

// ── Write: SlideAnimation[] → <p:timing> ───────────────────────────────

/** presetID/presetClass/presetSubtype (used by PowerPoint's animation pane to show effect names). */
const PRESET: Record<
  AnimEffectKind,
  { id: number; cls: 'entr' | 'emph' | 'exit' | 'path'; sub: number }
> = {
  appear: { id: 1, cls: 'entr', sub: 0 },
  fade: { id: 10, cls: 'entr', sub: 0 },
  flyIn: { id: 2, cls: 'entr', sub: 4 }, // from bottom
  wipe: { id: 22, cls: 'entr', sub: 1 }, // from bottom
  wipeDown: { id: 22, cls: 'entr', sub: 4 }, // from top
  splitIn: { id: 16, cls: 'entr', sub: 21 }, // expand left/right from center
  bounce: { id: 26, cls: 'entr', sub: 0 },
  flipIn: { id: 30, cls: 'entr', sub: 0 }, // flip in from far to near (Grow & Turn)
  zoom: { id: 23, cls: 'entr', sub: 16 },
  // classic filter families (official presetIDs; PowerPoint reads the filter strings)
  blinds: { id: 3, cls: 'entr', sub: 0 },
  box: { id: 4, cls: 'entr', sub: 0 },
  checkerboard: { id: 5, cls: 'entr', sub: 0 },
  circleIn: { id: 6, cls: 'entr', sub: 0 },
  crawlIn: { id: 7, cls: 'entr', sub: 0 },
  diamond: { id: 8, cls: 'entr', sub: 0 },
  dissolveIn: { id: 9, cls: 'entr', sub: 0 },
  randomBars: { id: 14, cls: 'entr', sub: 0 },
  stretch: { id: 17, cls: 'entr', sub: 4 }, // stretch up from the bottom edge
  strips: { id: 18, cls: 'entr', sub: 0 },
  wedge: { id: 20, cls: 'entr', sub: 0 },
  wheel: { id: 21, cls: 'entr', sub: 1 }, // 1 spoke (clock wipe)
  swivel: { id: 19, cls: 'entr', sub: 0 },
  peekIn: { id: 12, cls: 'entr', sub: 1 }, // peek from bottom
  pulse: { id: 26, cls: 'emph', sub: 0 },
  spin: { id: 8, cls: 'emph', sub: 0 },
  grow: { id: 6, cls: 'emph', sub: 0 },
  teeter: { id: 32, cls: 'emph', sub: 0 },
  disappear: { id: 1, cls: 'exit', sub: 0 },
  fadeOut: { id: 10, cls: 'exit', sub: 0 },
  flyOut: { id: 2, cls: 'exit', sub: 4 }, // to bottom
  wipeOut: { id: 22, cls: 'exit', sub: 1 },
  shrink: { id: 30, cls: 'exit', sub: 0 }, // shrink and rotate (Shrink & Turn)
  zoomOut: { id: 23, cls: 'exit', sub: 16 },
  boxOut: { id: 4, cls: 'exit', sub: 0 },
  checkerboardOut: { id: 5, cls: 'exit', sub: 0 },
  dissolveOut: { id: 9, cls: 'exit', sub: 0 },
  randomBarsOut: { id: 14, cls: 'exit', sub: 0 },
  motionPath: { id: 0, cls: 'path', sub: 0 }, // custom path
}

/** presetClass:presetID(:presetSubtype) → effect (read-back mapping; unmodeled ones map to a same-class approximation). */
export const ANIM_EFFECTS = Object.keys(PRESET) as readonly AnimEffectKind[]

const DIRECTIONAL: ReadonlySet<AnimEffectKind> = new Set(['flyIn', 'flyOut', 'wipe', 'wipeOut'])
/** PowerPoint's presetSubtype per side: fly uses 1/4/8/2 (top/bottom/left/right), wipe 4/1/8/2. */
const FLY_SUB: Record<AnimDirection, number> = { top: 1, bottom: 4, left: 8, right: 2 }
const WIPE_SUB: Record<AnimDirection, number> = { top: 4, bottom: 1, left: 8, right: 2 }

function presetSubtypeOf(a: SlideAnimation): number {
  if (!a.direction || !DIRECTIONAL.has(a.effect)) return PRESET[a.effect].sub
  return a.effect === 'flyIn' || a.effect === 'flyOut'
    ? FLY_SUB[a.direction]
    : WIPE_SUB[a.direction]
}

function directionFromPreset(effect: AnimEffectKind, sub: number): AnimDirection | undefined {
  if (!DIRECTIONAL.has(effect)) return undefined
  const table = effect === 'flyIn' || effect === 'flyOut' ? FLY_SUB : WIPE_SUB
  return (Object.keys(table) as AnimDirection[]).find((d) => table[d] === sub)
}

function modeledEffect(cls: string, id: number, sub: number): AnimEffectKind | null {
  if (cls === 'path') return 'motionPath'
  // Effects sharing a presetID distinguished by subtype (e.g. wipe direction)
  const bySub: Record<string, AnimEffectKind> = {
    'entr:22:1': 'wipe',
    'entr:22:4': 'wipeDown',
  }
  const exact: Record<string, AnimEffectKind> = {
    'entr:1': 'appear',
    'entr:10': 'fade',
    'entr:2': 'flyIn',
    'entr:22': 'wipe',
    'entr:16': 'splitIn',
    'entr:26': 'bounce',
    'entr:30': 'flipIn',
    'entr:23': 'zoom',
    'entr:3': 'blinds',
    'entr:4': 'box',
    'entr:5': 'checkerboard',
    'entr:6': 'circleIn',
    'entr:7': 'crawlIn',
    'entr:8': 'diamond',
    'entr:9': 'dissolveIn',
    'entr:14': 'randomBars',
    'entr:17': 'stretch',
    'entr:18': 'strips',
    'entr:20': 'wedge',
    'entr:21': 'wheel',
    'entr:19': 'swivel',
    'entr:12': 'peekIn',
    'emph:26': 'pulse',
    'emph:8': 'spin',
    'emph:6': 'grow',
    'emph:32': 'teeter',
    'exit:1': 'disappear',
    'exit:10': 'fadeOut',
    'exit:2': 'flyOut',
    'exit:22': 'wipeOut',
    'exit:30': 'shrink',
    'exit:23': 'zoomOut',
    'exit:4': 'boxOut',
    'exit:5': 'checkerboardOut',
    'exit:9': 'dissolveOut',
    'exit:14': 'randomBarsOut',
  }
  return bySub[`${cls}:${id}:${sub}`] ?? exact[`${cls}:${id}`] ?? null
}

function effectFromPreset(cls: string, id: number, sub: number): AnimEffectKind {
  const hit = modeledEffect(cls, id, sub)
  if (hit) return hit
  if (cls === 'exit') return 'fadeOut'
  if (cls === 'emph') return 'pulse'
  return 'fade'
}

const NODE_TYPE: Record<AnimTrigger, string> = {
  onClick: 'clickEffect',
  withPrev: 'withEffect',
  afterPrev: 'afterEffect',
}

interface IdGen {
  next: () => number
}

/**
 * Behavior target <p:tgtEl>. With paragraph, adds txEl/pgRg: ECMA-376
 * CT_IndexRange's st/end are 0-based paragraph indices (files generated by
 * PowerPoint use st="0" for the first paragraph), mapping directly.
 */
function tgtElXml(a: SlideAnimation): string {
  const inner =
    a.paragraph == null
      ? `<p:spTgt spid="${a.spid}"/>`
      : `<p:spTgt spid="${a.spid}"><p:txEl><p:pgRg st="${a.paragraph}" end="${a.paragraph}"/></p:txEl></p:spTgt>`
  return `<p:tgtEl>${inner}</p:tgtEl>`
}

/** Set style.visibility (entrance=visible / exit=hidden). delay is relative to the effect start. */
function setVisibilityXml(gen: IdGen, tgt: string, visible: boolean, delayMs: number): string {
  return (
    '<p:set><p:cBhvr>' +
    `<p:cTn id="${gen.next()}" dur="1" fill="hold"><p:stCondLst><p:cond delay="${delayMs}"/></p:stCondLst></p:cTn>` +
    tgt +
    '<p:attrNameLst><p:attrName>style.visibility</p:attrName></p:attrNameLst>' +
    `</p:cBhvr><p:to><p:strVal val="${visible ? 'visible' : 'hidden'}"/></p:to></p:set>`
  )
}

/** Attribute keyframe animation (tm is a per-mille time point 0..100000, val a formula string). */
function keyframeAnimXml(
  gen: IdGen,
  tgt: string,
  dur: number,
  attr: string,
  frames: Array<[tm: number, val: string]>,
): string {
  const tavs = frames
    .map(([tm, val]) => `<p:tav tm="${tm}"><p:val><p:strVal val="${val}"/></p:val></p:tav>`)
    .join('')
  return (
    '<p:anim calcmode="lin" valueType="num">' +
    `<p:cBhvr additive="base"><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>` +
    tgt +
    `<p:attrNameLst><p:attrName>${attr}</p:attrName></p:attrNameLst></p:cBhvr>` +
    `<p:tavLst>${tavs}</p:tavLst></p:anim>`
  )
}

/** ppt_x/ppt_y translation animation (for fly in/out). */
function moveAnimXml(
  gen: IdGen,
  tgt: string,
  dur: number,
  attr: 'ppt_x' | 'ppt_y',
  from: string,
  to: string,
): string {
  return keyframeAnimXml(gen, tgt, dur, attr, [
    [0, from],
    [100000, to],
  ])
}

/** Default motionPath (straight line to the right, 1/4 of the slide width). */
export const DEFAULT_MOTION_PATH = 'M 0 0 L 0.25 0'

/** Off-slide position a fly effect starts from / ends at, per side. */
function flyOffscreen(d: AnimDirection): { x: string; y: string } {
  switch (d) {
    case 'top':
      return { x: '#ppt_x', y: '0-#ppt_h/2' }
    case 'left':
      return { x: '0-#ppt_w/2', y: '#ppt_y' }
    case 'right':
      return { x: '1+#ppt_w/2', y: '#ppt_y' }
    default:
      return { x: '#ppt_x', y: '1+#ppt_h/2' }
  }
}
/** animEffect wipe filter: the reveal moves away from the side it comes from; exits run the reverse. */
const WIPE_IN_FILTER: Record<AnimDirection, string> = {
  top: 'down',
  bottom: 'up',
  left: 'right',
  right: 'left',
}
const WIPE_OUT_FILTER: Record<AnimDirection, string> = {
  top: 'up',
  bottom: 'down',
  left: 'left',
  right: 'right',
}

/** Move along a path (<p:animMotion>); the path gets the " E" end marker per OOXML convention. */
function motionAnimXml(gen: IdGen, tgt: string, dur: number, path: string): string {
  const p = path.trim() || DEFAULT_MOTION_PATH
  const pathAttr = /\bE$/.test(p) ? p : `${p} E`
  return (
    `<p:animMotion origin="layout" path="${pathAttr}" pathEditMode="relative">` +
    `<p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>` +
    tgt +
    '<p:attrNameLst><p:attrName>ppt_x</p:attrName><p:attrName>ppt_y</p:attrName></p:attrNameLst>' +
    '</p:cBhvr></p:animMotion>'
  )
}

/** Behavior list of one effect (a combination of set/animEffect/anim/animScale/animRot). */
function effectBehaviorsXml(gen: IdGen, a: SlideAnimation): string {
  const dur = Math.max(1, Math.round(a.durationMs))
  const target = tgtElXml(a)
  const show = setVisibilityXml(gen, target, true, 0)
  const hideAtEnd = setVisibilityXml(gen, target, false, Math.max(0, dur - 1))
  switch (a.effect) {
    case 'appear':
      return show
    case 'fade':
      return (
        show +
        `<p:animEffect transition="in" filter="fade"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>`
      )
    case 'flyIn': {
      const off = flyOffscreen(a.direction ?? 'bottom')
      return (
        show +
        moveAnimXml(gen, target, dur, 'ppt_x', off.x, '#ppt_x') +
        moveAnimXml(gen, target, dur, 'ppt_y', off.y, '#ppt_y')
      )
    }
    case 'wipe':
      return (
        show +
        `<p:animEffect transition="in" filter="wipe(${WIPE_IN_FILTER[a.direction ?? 'bottom']})"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>`
      )
    case 'wipeDown':
      return (
        show +
        `<p:animEffect transition="in" filter="wipe(down)"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>`
      )
    case 'splitIn':
      return (
        show +
        `<p:animEffect transition="in" filter="split(inHorizontal)"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>`
      )
    case 'bounce':
      // Drop from above + damped rebound (ppt_y keyframes approximating PowerPoint's bounce)
      return (
        show +
        keyframeAnimXml(gen, target, dur, 'ppt_y', [
          [0, '#ppt_y-0.25'],
          [55000, '#ppt_y'],
          [70000, '#ppt_y-0.08'],
          [85000, '#ppt_y'],
          [92000, '#ppt_y-0.03'],
          [100000, '#ppt_y'],
        ])
      )
    case 'flipIn':
      // Expand horizontally from 0 + fade in (approximation of Grow & Turn)
      return (
        show +
        `<p:animEffect transition="in" filter="fade"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:from x="0" y="100000"/><p:to x="100000" y="100000"/></p:animScale>'
      )
    case 'zoom':
      return (
        show +
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:from x="0" y="0"/><p:to x="100000" y="100000"/></p:animScale>'
      )
    case 'pulse':
      return (
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${Math.max(1, Math.round(dur / 2))}" autoRev="1" fill="hold"/>${target}</p:cBhvr>` +
        '<p:by x="106000" y="106000"/></p:animScale>'
      )
    case 'spin':
      return (
        `<p:animRot by="21600000"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}` +
        '<p:attrNameLst><p:attrName>r</p:attrName></p:attrNameLst></p:cBhvr></p:animRot>'
      )
    case 'grow':
      return (
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:by x="150000" y="150000"/></p:animScale>'
      )
    case 'teeter':
      // Teeter: rock left/right around its own angle, then settle back
      return keyframeAnimXml(gen, target, dur, 'ppt_r', [
        [0, '#ppt_r'],
        [12500, '#ppt_r-9'],
        [37500, '#ppt_r+9'],
        [62500, '#ppt_r-6'],
        [87500, '#ppt_r+3'],
        [100000, '#ppt_r'],
      ])
    case 'disappear':
      return setVisibilityXml(gen, target, false, 0)
    case 'fadeOut':
      return (
        `<p:animEffect transition="out" filter="fade"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'flyOut': {
      const off = flyOffscreen(a.direction ?? 'bottom')
      return (
        moveAnimXml(gen, target, dur, 'ppt_x', '#ppt_x', off.x) +
        moveAnimXml(gen, target, dur, 'ppt_y', '#ppt_y', off.y) +
        hideAtEnd
      )
    }
    case 'wipeOut':
      return (
        `<p:animEffect transition="out" filter="wipe(${WIPE_OUT_FILTER[a.direction ?? 'bottom']})"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'shrink':
      // Shrink and rotate out (approximation of Shrink & Turn)
      return (
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:from x="100000" y="100000"/><p:to x="1000" y="1000"/></p:animScale>' +
        `<p:animRot by="-5400000"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}` +
        '<p:attrNameLst><p:attrName>r</p:attrName></p:attrNameLst></p:cBhvr></p:animRot>' +
        hideAtEnd
      )
    case 'zoomOut':
      return (
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:from x="100000" y="100000"/><p:to x="1000" y="1000"/></p:animScale>' +
        hideAtEnd
      )
    // ── classic animEffect filter families (PowerPoint plays the filter attribute) ──
    case 'blinds':
    case 'box':
    case 'checkerboard':
    case 'circleIn':
    case 'diamond':
    case 'dissolveIn':
    case 'randomBars':
    case 'strips':
    case 'wedge':
    case 'wheel':
      return (
        show +
        `<p:animEffect transition="in" filter="${animEffectFilter(a.effect, a.variant)}"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>`
      )
    case 'crawlIn': {
      // Crawl in from an edge (slow slide, no filter); 效果选项 picks the edge
      const side = a.variant ?? 'left'
      const offX = side === 'left' ? '0-#ppt_w/2' : side === 'right' ? '1+#ppt_w/2' : '#ppt_x'
      const offY = side === 'top' ? '0-#ppt_h/2' : side === 'bottom' ? '1+#ppt_h/2' : '#ppt_y'
      return (
        show +
        moveAnimXml(gen, target, dur, 'ppt_x', offX, '#ppt_x') +
        moveAnimXml(gen, target, dur, 'ppt_y', offY, '#ppt_y')
      )
    }
    case 'stretch':
      // Stretch up from the bottom edge (vertical scale 0→100%)
      return (
        show +
        `<p:animScale><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}</p:cBhvr>` +
        '<p:from x="100000" y="0"/><p:to x="100000" y="100000"/></p:animScale>'
      )
    case 'boxOut':
      return (
        `<p:animEffect transition="out" filter="${animEffectFilter('box', a.variant === 'in' ? 'in' : 'out')}"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'checkerboardOut':
      return (
        `<p:animEffect transition="out" filter="checkerboard(across)"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'dissolveOut':
      return (
        `<p:animEffect transition="out" filter="dissolve"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'randomBarsOut':
      return (
        `<p:animEffect transition="out" filter="${animEffectFilter('randomBars', a.variant)}"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        hideAtEnd
      )
    case 'swivel':
      // Swivel: unroll around the vertical axis — full rotation (like spin) so
      // PowerPoint's pane labels it Swivel; canvas approximates with an x-flip
      return (
        show +
        `<p:animRot by="21600000"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}" fill="hold"/>${target}` +
        '<p:attrNameLst><p:attrName>r</p:attrName></p:attrNameLst></p:cBhvr></p:animRot>'
      )
    case 'peekIn':
      // Peek In: wipe reveal + a small slide-in offset toward the reveal edge
      return (
        show +
        `<p:animEffect transition="in" filter="wipe(up)"><p:cBhvr><p:cTn id="${gen.next()}" dur="${dur}"/>${target}</p:cBhvr></p:animEffect>` +
        moveAnimXml(gen, target, dur, 'ppt_y', '#ppt_y+0.06', '#ppt_y')
      )
    case 'motionPath':
      return motionAnimXml(gen, target, dur, a.motionPath ?? DEFAULT_MOTION_PATH)
  }
}

/**
 * Build the whole <p:timing>. Grouping rules (matching slideshow playback):
 * onClick starts a new "click group"; withPrev joins the current group (start =
 * previous effect's start + delay); afterPrev joins the current group (start =
 * previous effect's end + delay). If the first item is not onClick, group 0
 * plays automatically after the slide transition (stCondLst delay=0).
 */
interface Placed {
  a: SlideAnimation
  startMs: number
  grpId: number
}

/**
 * Grouping + absolute in-group start: onClick starts a new "click group"; withPrev
 * start = previous start + delay; afterPrev start = previous end + delay.
 * grpBase = animation count already used per spid (continued on incremental append).
 */
function placeAnims(
  anims: SlideAnimation[],
  grpBase?: Map<number, number>,
): Array<{ auto: boolean; items: Placed[] }> {
  const groups: Array<{ auto: boolean; items: Placed[] }> = []
  const grpCount = new Map<number, number>(grpBase ?? [])
  let prevStart = 0
  let prevEnd = 0
  for (const a of anims) {
    if (a.trigger === 'onClick' || groups.length === 0) {
      groups.push({ auto: a.trigger !== 'onClick', items: [] })
      prevStart = 0
      prevEnd = 0
    }
    const base = a.trigger === 'afterPrev' ? prevEnd : a.trigger === 'withPrev' ? prevStart : 0
    const start = base + Math.max(0, Math.round(a.delayMs))
    const grpId = grpCount.get(a.spid) ?? 0
    grpCount.set(a.spid, grpId + 1)
    groups[groups.length - 1]!.items.push({ a, startMs: start, grpId })
    prevStart = start
    prevEnd = start + Math.max(1, Math.round(a.durationMs))
  }
  return groups
}

/** One effect's <p:par> (cTn with presetID/presetClass + start + behaviors). */
function effectParXml(gen: IdGen, p: Placed): string {
  if (p.a.presetXml) return placePresetXml(gen, p)
  const preset = PRESET[p.a.effect]
  // 效果选项变体覆盖默认 presetSubtype (animation-pane label metadata)
  const sub = p.a.direction
    ? presetSubtypeOf(p.a)
    : animVariantSubtype(p.a.effect, p.a.variant) || preset.sub
  // 播完快退 (WPS 动画属性·播完动画后快退): after the effect, hide the shape
  // again (cond delay = duration; PowerPoint encodes 播完后快退 the same way)
  const rewindXml = p.a.rewind
    ? setVisibilityXml(gen, tgtElXml(p.a), false, Math.max(1, Math.round(p.a.durationMs)))
    : ''
  return (
    '<p:par>' +
    `<p:cTn id="${gen.next()}" presetID="${preset.id}" presetClass="${preset.cls}" presetSubtype="${sub}" fill="hold" grpId="${p.grpId}" nodeType="${NODE_TYPE[p.a.trigger]}">` +
    `<p:stCondLst><p:cond delay="${p.startMs}"/></p:stCondLst>` +
    `<p:childTnLst>${effectBehaviorsXml(gen, p.a)}${rewindXml}</p:childTnLst>` +
    '</p:cTn></p:par>'
  )
}

/**
 * A verbatim effect <p:par> re-placed in the rebuilt sequence: cTn ids are renumbered
 * into the slide's id space and the outer cTn takes the list's trigger, group and
 * start; the behaviors inside keep their original bytes.
 */
function placePresetXml(gen: IdGen, p: Placed): string {
  let xml = p.a.presetXml!.replace(
    /(<p:cTn\b[^>]*?\bid=")\d+(")/g,
    (_m, a, b) => `${a}${gen.next()}${b}`,
  )
  xml = xml.replace(/<p:cTn\b[^>]*>/, (open) => {
    let o = open.replace(/\s(?:grpId|nodeType)="[^"]*"/g, '')
    o = o.replace(/>$/, ` grpId="${p.grpId}" nodeType="${NODE_TYPE[p.a.trigger]}">`)
    return o
  })
  return xml.replace(/(<p:stCondLst><p:cond delay=")[^"]*(")/, (_m, a, b) => `${a}${p.startMs}${b}`)
}

/** The two-level <p:par> wrapper of one "click group". */
function groupParXml(gen: IdGen, g: { auto: boolean; items: Placed[] }): string {
  const effects = g.items.map((p) => effectParXml(gen, p)).join('')
  return (
    '<p:par>' +
    `<p:cTn id="${gen.next()}" fill="hold">` +
    `<p:stCondLst><p:cond delay="${g.auto ? '0' : 'indefinite'}"/></p:stCondLst>` +
    '<p:childTnLst><p:par>' +
    `<p:cTn id="${gen.next()}" fill="hold"><p:stCondLst><p:cond delay="0"/></p:stCondLst>` +
    `<p:childTnLst>${effects}</p:childTnLst></p:cTn>` +
    '</p:par></p:childTnLst></p:cTn></p:par>'
  )
}

/**
 * bldP list for a full rebuild (shapes with paragraph animation get a single
 * summarizing build="p" bldP instead of one plain bldP per grpId).
 */
function bldPsXml(anims: SlideAnimation[]): string {
  const paraSpids = new Set(anims.filter((a) => a.paragraph != null).map((a) => a.spid))
  const bldSeen = new Set<string>()
  return anims
    .map((a, i) => {
      if (paraSpids.has(a.spid)) {
        const key = `p:${a.spid}`
        if (bldSeen.has(key)) return ''
        bldSeen.add(key)
        // grpId=0: on a full rebuild the spid's first animation always has grpId 0
        return `<p:bldP spid="${a.spid}" grpId="0" uiExpand="1" build="p"/>`
      }
      // grpId matches effect generation: the nth animation of the same spid has grpId=n
      const before = anims.slice(0, i).filter((x) => x.spid === a.spid).length
      const key = `${a.spid}:${before}`
      if (bldSeen.has(key)) return ''
      bldSeen.add(key)
      return `<p:bldP spid="${a.spid}" grpId="${before}"/>`
    })
    .join('')
}

export function buildTimingXml(anims: SlideAnimation[]): string {
  if (anims.length === 0) return ''
  let idCounter = 0
  const gen: IdGen = { next: () => ++idCounter }
  const rootId = gen.next() // 1 tmRoot
  const seqId = gen.next() // 2 mainSeq

  const groupXml = placeAnims(anims)
    .map((g) => groupParXml(gen, g))
    .join('')

  const bldPs = bldPsXml(anims)

  return (
    '<p:timing><p:tnLst><p:par>' +
    `<p:cTn id="${rootId}" dur="indefinite" restart="never" nodeType="tmRoot"><p:childTnLst>` +
    '<p:seq concurrent="1" nextAc="seek">' +
    `<p:cTn id="${seqId}" dur="indefinite" nodeType="mainSeq"><p:childTnLst>${groupXml}</p:childTnLst></p:cTn>` +
    '<p:prevCondLst><p:cond evt="onPrev" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:prevCondLst>' +
    '<p:nextCondLst><p:cond evt="onNext" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:nextCondLst>' +
    '</p:seq></p:childTnLst></p:cTn>' +
    '</p:par></p:tnLst>' +
    `<p:bldLst>${bldPs}</p:bldLst></p:timing>`
  )
}

const TIMING_RE = /<p:timing\b[^>]*\/>|<p:timing\b[^>]*>[\s\S]*?<\/p:timing>/

/** Content span of the mainSeq cTn; returns null when there is no main sequence. */
function mainSeqSpan(timing: string): { start: number; end: number } | null {
  const m = /<p:cTn\b[^>]*\bnodeType="mainSeq"[^>]*>/.exec(timing)
  if (!m) return null
  const start = m.index + m[0].length
  return { start, end: findCTnEnd(timing, start) }
}

/** Whether the tmRoot cTn's childTnLst has no children left (after removing the main sequence, decides whether the whole timing is still meaningful). */
function rootChildTnLstEmpty(timing: string): boolean {
  const rootM = /<p:cTn\b[^>]*\bnodeType="tmRoot"[^>]*>/.exec(timing)
  if (!rootM) return true
  const childOpen = timing.indexOf('<p:childTnLst>', rootM.index + rootM[0].length)
  if (childOpen < 0) return true
  const childClose = findBalancedClose(timing, childOpen, 'p:childTnLst')
  if (childClose < 0) return true
  return !timing.slice(childOpen + '<p:childTnLst>'.length, childClose).trim()
}

/** Strip all <p:bldP> from bldLst and write ours; bldDgm/bldOleChart/bldGraphic etc. are kept. */
function rebuildBldLst(timing: string, anims: SlideAnimation[]): string {
  const ours = bldPsXml(anims)
  const bldOpen = /<p:bldLst\b[^>]*>/.exec(timing)
  if (!bldOpen) {
    if (!ours) return timing
    const tEnd = timing.lastIndexOf('</p:timing>')
    if (tEnd < 0) return timing
    return timing.slice(0, tEnd) + `<p:bldLst>${ours}</p:bldLst>` + timing.slice(tEnd)
  }
  const close = findBalancedClose(timing, bldOpen.index, 'p:bldLst')
  if (close < 0) return timing
  const inner = timing.slice(bldOpen.index + bldOpen[0].length, close)
  const kept = inner.replace(/<p:bldP\b[^>]*\/>|<p:bldP\b[^>]*>[\s\S]*?<\/p:bldP>/g, '')
  const newInner = ours + kept
  const replacement = newInner ? `<p:bldLst>${newInner}</p:bldLst>` : ''
  return timing.slice(0, bldOpen.index) + replacement + timing.slice(close + '</p:bldLst>'.length)
}

/**
 * Overwrite-style rebuild that only touches the main sequence: the mainSeq childTnLst
 * is replaced with new effect groups; unmodeled siblings (interactiveSeq, media
 * timelines, ...) keep their original bytes; bldP is rewritten, other bld* kept.
 * Empty anims removes the whole <p:seq> (main sequence); if the root childTnLst becomes
 * empty as a result, returns '' (delete the timing).
 * Returns null when the structure is unexpected; the caller falls back to a fresh build.
 */
function rebuildTimingPreservingXml(timing: string, anims: SlideAnimation[]): string | null {
  const seqCtnM = /<p:cTn\b[^>]*\bnodeType="mainSeq"[^>]*>/.exec(timing)
  let newTiming: string
  if (anims.length === 0) {
    if (!seqCtnM) return rebuildBldLst(timing, anims)
    const seqStart = timing.lastIndexOf('<p:seq', seqCtnM.index)
    if (seqStart < 0) return null
    const seqClose = findBalancedClose(timing, seqStart, 'p:seq')
    if (seqClose < 0) return null
    newTiming = timing.slice(0, seqStart) + timing.slice(seqClose + '</p:seq>'.length)
    newTiming = rebuildBldLst(newTiming, anims)
    return rootChildTnLstEmpty(newTiming) ? '' : newTiming
  }

  const gen = makeGenAfterMaxId(timing)
  const groupXml = placeAnims(anims)
    .map((g) => groupParXml(gen, g))
    .join('')
  if (seqCtnM) {
    const childOpen = timing.indexOf('<p:childTnLst>', seqCtnM.index + seqCtnM[0].length)
    if (childOpen < 0) return null
    const childClose = findBalancedClose(timing, childOpen, 'p:childTnLst')
    if (childClose < 0) return null
    newTiming =
      timing.slice(0, childOpen + '<p:childTnLst>'.length) + groupXml + timing.slice(childClose)
  } else {
    // Original timing has no main sequence (only trigger/media nodes): insert a brand-new <p:seq> at the end of the tmRoot childTnLst
    const rootM = /<p:cTn\b[^>]*\bnodeType="tmRoot"[^>]*>/.exec(timing)
    if (!rootM) return null
    const childOpen = timing.indexOf('<p:childTnLst>', rootM.index + rootM[0].length)
    if (childOpen < 0) return null
    const childClose = findBalancedClose(timing, childOpen, 'p:childTnLst')
    if (childClose < 0) return null
    const seqXml =
      '<p:seq concurrent="1" nextAc="seek">' +
      `<p:cTn id="${gen.next()}" dur="indefinite" nodeType="mainSeq"><p:childTnLst>${groupXml}</p:childTnLst></p:cTn>` +
      '<p:prevCondLst><p:cond evt="onPrev" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:prevCondLst>' +
      '<p:nextCondLst><p:cond evt="onNext" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:nextCondLst>' +
      '</p:seq>'
    newTiming = timing.slice(0, childClose) + seqXml + timing.slice(childClose)
  }
  return rebuildBldLst(newTiming, anims)
}

/**
 * In-place patch of the bodySuffix's <p:timing> (schema order: after transition, before extLst).
 * With an existing timing, only the main sequence is rebuilt and unmodeled sibling
 * nodes are kept; empty anims removes the main sequence (the timing stays if other
 * nodes remain, and is removed only when fully empty). Returns the new bodySuffix.
 */
export function patchSlideTimingXml(bodySuffix: string, anims: SlideAnimation[]): string {
  const timingM = TIMING_RE.exec(bodySuffix)
  if (timingM) {
    const rebuilt = rebuildTimingPreservingXml(timingM[0], anims)
    if (rebuilt != null)
      return (
        bodySuffix.slice(0, timingM.index) +
        rebuilt +
        bodySuffix.slice(timingM.index + timingM[0].length)
      )
  }
  const stripped = bodySuffix.replace(TIMING_RE, '')
  if (anims.length === 0) return stripped
  const xml = buildTimingXml(anims)
  // Insertion point: before </p:sld>; with a slide-level <p:extLst> (legal after
  // timing, but PowerPoint emits timing first), insert before the last extLst
  const ext = stripped.lastIndexOf('<p:extLst')
  const sldEnd = stripped.lastIndexOf('</p:sld>')
  const at = ext >= 0 ? ext : sldEnd
  if (at < 0) return stripped
  return stripped.slice(0, at) + xml + stripped.slice(at)
}

// ── Read: <p:timing> → SlideAnimation[] ────────────────────────────────

/** Balanced scan: from openEnd (end of the open tag) find the matching </p:cTn>, returning the content end. */
function findCTnEnd(xml: string, openEnd: number): number {
  const re = /<p:cTn\b[^>]*?(\/?)>|<\/p:cTn>/g
  re.lastIndex = openEnd
  let depth = 1
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    if (m[0] === '</p:cTn>') {
      depth--
      if (depth === 0) return m.index
    } else if (m[1] !== '/') {
      depth++
    }
  }
  return xml.length
}

/** crawlIn edge read-back: which ppt_x/ppt_y keyframe deviates from #ppt_x/#ppt_y. */
function crawlVariantOf(body: string): string | undefined {
  if (/ppt_x[\s\S]*?val="0-#ppt_w\/2"/.test(body)) return 'left'
  if (/ppt_x[\s\S]*?val="1+#ppt_w\/2"/.test(body)) return 'right'
  if (/ppt_y[\s\S]*?val="0-#ppt_h\/2"/.test(body)) return 'top'
  if (/ppt_y[\s\S]*?val="1+#ppt_h\/2"/.test(body)) return 'bottom'
  return 'left'
}

/**
 * Read the bodySuffix's animation list (for UI echo + slideshow).
 * Parses every effect cTn carrying presetClass; delay is derived back to the user
 * delay per the write convention (withPrev minus previous start / afterPrev minus
 * previous end).
 */
export function readSlideTimingXml(bodySuffix: string): SlideAnimation[] {
  const timing = TIMING_RE.exec(bodySuffix)?.[0]
  if (!timing) return []
  // Read only the main sequence: interactiveSeq trigger animations etc. are not modeled, avoiding mistakenly absorbing them as click animations on rewrite
  const seq = mainSeqSpan(timing)
  if (!seq) return []
  const out: SlideAnimation[] = []
  const re = /<p:cTn\b([^>]*\bpresetClass="[^"]*"[^>]*)>/g
  re.lastIndex = seq.start
  let m: RegExpExecArray | null
  let prevStart = 0
  let prevEnd = 0
  while ((m = re.exec(timing)) !== null && m.index < seq.end) {
    const attrs = m[1]!
    const cls = /\bpresetClass="([^"]*)"/.exec(attrs)?.[1] ?? 'entr'
    const pid = Number(/\bpresetID="(\d+)"/.exec(attrs)?.[1] ?? '0')
    const psub = Number(/\bpresetSubtype="(\d+)"/.exec(attrs)?.[1] ?? '0')
    const nodeType = /\bnodeType="([^"]*)"/.exec(attrs)?.[1] ?? 'clickEffect'
    const trigger: AnimTrigger =
      nodeType === 'withEffect' ? 'withPrev' : nodeType === 'afterEffect' ? 'afterPrev' : 'onClick'
    const bodyEnd = findCTnEnd(timing, re.lastIndex)
    const body = timing.slice(re.lastIndex, bodyEnd)
    re.lastIndex = bodyEnd

    const spidM = /<p:spTgt\s[^>]*\bspid="(\d+)"/.exec(body)
    if (!spidM) continue
    const spid = Number(spidM[1])
    // Start: the effect cTn's own stCondLst (first cond delay at the body start)
    const startMs = Number(/^\s*<p:stCondLst><p:cond delay="(\d+)"/.exec(body)?.[1] ?? '0')
    // Duration: the largest numeric dur among the behaviors
    let durationMs = 0
    const durRe = /\bdur="(\d+)"/g
    let dm: RegExpExecArray | null
    while ((dm = durRe.exec(body)) !== null) durationMs = Math.max(durationMs, Number(dm[1]))
    // pulse with autoRev: actual duration = dur*2
    if (/\bautoRev="1"/.test(body)) durationMs *= 2
    const effect = effectFromPreset(cls, pid, psub)
    if (effect === 'appear' || effect === 'disappear') durationMs = 0
    const modeled = modeledEffect(cls, pid, psub) != null
    const parStart = timing.lastIndexOf('<p:par', m.index)
    const parClose = parStart >= 0 ? findBalancedClose(timing, parStart, 'p:par') : -1

    if (trigger === 'onClick') {
      prevStart = 0
      prevEnd = 0
    }
    const base = trigger === 'afterPrev' ? prevEnd : trigger === 'withPrev' ? prevStart : 0
    const delayMs = Math.max(0, startMs - base)
    prevStart = startMs
    prevEnd = startMs + Math.max(1, durationMs)

    const anim: SlideAnimation = { spid, effect, trigger, durationMs, delayMs }
    const direction = directionFromPreset(effect, psub)
    if (direction && psub !== PRESET[effect].sub) anim.direction = direction
    if (!modeled && parStart >= 0 && parClose >= 0) {
      anim.presetXml = timing.slice(parStart, parClose + '</p:par>'.length)
      anim.preset = { id: pid, cls, sub: psub }
    }
    const pgM = /<p:pgRg\s[^>]*\bst="(\d+)"/.exec(body)
    if (pgM) anim.paragraph = Number(pgM[1])
    // 效果选项 echo: the filter argument carries the variant (crawlIn has no
    // filter — its edge is read back from the ppt_x/ppt_y keyframe origin)
    if (ANIM_VARIANTS[effect]) {
      const filter = /<p:animEffect\b[^>]*\bfilter="([^"]*)"/.exec(body)?.[1]
      const variant = filter ? animVariantFromFilter(effect, filter) : crawlVariantOf(body)
      if (variant) anim.variant = variant
    }
    if (effect === 'motionPath') {
      // Path read-back: drop the " E" end marker added on write, restoring the user path
      const path = /<p:animMotion\b[^>]*\bpath="([^"]*)"/.exec(body)?.[1]
      anim.motionPath = (path ?? DEFAULT_MOTION_PATH).replace(/\s*E$/, '').trim()
    }
    // 播完快退 echo: an extra hide set at delay≈duration. Only meaningful on
    // entrance/emphasis effects — exit effects (fadeOut/flyOut/wipeOut/shrink/
    // zoomOut/disappear) always carry that hide themselves (hideAtEnd).
    if (animClassOf(effect) !== 'exit') {
      const hideRe = new RegExp(
        `<p:set><p:cBhvr><p:cTn[^>]*><p:stCondLst><p:cond delay="${Math.max(0, durationMs - 1)}"/></p:stCondLst>[\\s\\S]*?<p:strVal val="hidden"/>`,
      )
      if (hideRe.test(body)) anim.rewind = true
    }
    out.push(anim)
  }
  return out
}

// ── Incremental write-back (keeps unmodeled timing nodes) ──────────────

function animEq(x: SlideAnimation, y: SlideAnimation): boolean {
  return (
    x.spid === y.spid &&
    x.effect === y.effect &&
    x.trigger === y.trigger &&
    x.durationMs === y.durationMs &&
    x.delayMs === y.delayMs &&
    (x.motionPath ?? null) === (y.motionPath ?? null) &&
    (x.paragraph ?? null) === (y.paragraph ?? null) &&
    (x.variant ?? null) === (y.variant ?? null) &&
    !!x.rewind === !!y.rewind &&
    (x.direction ?? null) === (y.direction ?? null) &&
    (x.presetXml ?? null) === (y.presetXml ?? null)
  )
}

/** Balanced scan for the matching close tag: openStart points at the '<' of <tag …>; returns the start of </tag>, or -1 if not found. */
function findBalancedClose(xml: string, openStart: number, tag: string): number {
  const re = new RegExp(`<${tag}\\b[^>]*?(/?)>|</${tag}>`, 'g')
  re.lastIndex = openStart
  let depth = 0
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    if (m[0].startsWith(`</`)) {
      depth--
      if (depth === 0) return m.index
    } else if (m[1] !== '/') {
      depth++
    }
  }
  return -1
}

/** Span in the timing of the nth effect <p:par> (cTn with presetClass inside the main sequence); order matches readSlideTimingXml. */
function nthEffectParSpan(timing: string, n: number): { start: number; end: number } | null {
  const seq = mainSeqSpan(timing)
  if (!seq) return null
  const re = /<p:cTn\b[^>]*\bpresetClass="[^"]*"[^>]*>/g
  re.lastIndex = seq.start
  let m: RegExpExecArray | null
  let i = 0
  while ((m = re.exec(timing)) !== null && m.index < seq.end) {
    if (i++ < n) {
      re.lastIndex = findCTnEnd(timing, re.lastIndex)
      continue
    }
    const parStart = timing.lastIndexOf('<p:par', m.index)
    if (parStart < 0) return null
    const closeAt = findBalancedClose(timing, parStart, 'p:par')
    if (closeAt < 0) return null
    return { start: parStart, end: closeAt + '</p:par>'.length }
  }
  return null
}

/** Replay the grouping semantics to compute each animation's absolute in-group start (same as placeAnims). */
function absStarts(anims: SlideAnimation[]): number[] {
  const out: number[] = []
  let prevStart = 0
  let prevEnd = 0
  for (const a of anims) {
    if (a.trigger === 'onClick') {
      prevStart = 0
      prevEnd = 0
    }
    const base = a.trigger === 'afterPrev' ? prevEnd : a.trigger === 'withPrev' ? prevStart : 0
    const start = base + Math.max(0, Math.round(a.delayMs))
    out.push(start)
    prevStart = start
    prevEnd = start + Math.max(1, Math.round(a.durationMs))
  }
  return out
}

/** Largest numeric id already in the timing; incrementally generated cTn ids continue after it (unique within the slide). */
function makeGenAfterMaxId(timing: string): IdGen {
  let maxId = 0
  for (const m of timing.matchAll(/\bid="(\d+)"/g)) maxId = Math.max(maxId, Number(m[1]))
  let c = maxId
  return { next: () => ++c }
}

/** Append bldP into <p:bldLst> (created before </p:timing> if missing). Existing (spid,grpId) pairs are skipped. */
function appendBldPs(timing: string, items: Placed[]): string {
  const seen = new Set<string>()
  for (const m of timing.matchAll(/<p:bldP\b[^>]*\bspid="(\d+)"[^>]*\bgrpId="(\d+)"/g)) {
    seen.add(`${m[1]}:${m[2]}`)
  }
  // spids already having build="p": write only one paragraph bldP per shape
  const paraSeen = new Set<string>()
  for (const m of timing.matchAll(/<p:bldP\b[^>]*\bspid="(\d+)"[^>]*\bbuild="p"/g))
    paraSeen.add(m[1]!)
  const parts: string[] = []
  for (const p of items) {
    if (p.a.paragraph != null) {
      const k = String(p.a.spid)
      if (paraSeen.has(k)) continue
      paraSeen.add(k)
      parts.push(`<p:bldP spid="${p.a.spid}" grpId="${p.grpId}" uiExpand="1" build="p"/>`)
    } else {
      const k = `${p.a.spid}:${p.grpId}`
      if (seen.has(k)) continue
      seen.add(k)
      parts.push(`<p:bldP spid="${p.a.spid}" grpId="${p.grpId}"/>`)
    }
  }
  const add = parts.join('')
  if (!add) return timing
  const bldEnd = timing.lastIndexOf('</p:bldLst>')
  if (bldEnd >= 0) return timing.slice(0, bldEnd) + add + timing.slice(bldEnd)
  const tEnd = timing.lastIndexOf('</p:timing>')
  if (tEnd < 0) return timing
  return timing.slice(0, tEnd) + `<p:bldLst>${add}</p:bldLst>` + timing.slice(tEnd)
}

/**
 * Incremental <p:timing> patch: touches only the affected effect nodes; unmodeled
 * sibling nodes (interactive trigger sequences, text-level animations, media
 * timelines, ...) keep their original bytes. Two supported shapes:
 *   A. Pure append (old list is a prefix of the new one, and the first added item
 *      is onClick) → new click groups are inserted at the end of the mainSeq;
 *   B. Tail single-item edit (same length, only one item changed, trigger/target
 *      unchanged, and no chained dependency after it) → replace that effect's
 *      <p:par> wholesale.
 * Everything else (delete/reorder/trigger change) returns null and the caller
 * falls back to a full rebuild.
 */
export function patchSlideTimingIncrementalXml(
  bodySuffix: string,
  anims: SlideAnimation[],
): string | null {
  const timingM = TIMING_RE.exec(bodySuffix)
  if (!timingM) return null
  const timing = timingM[0]
  const old = readSlideTimingXml(bodySuffix)
  if (!old.length || !anims.length) return null
  const splice = (newTiming: string) =>
    bodySuffix.slice(0, timingM.index) + newTiming + bodySuffix.slice(timingM.index + timing.length)

  // A. Pure append
  if (anims.length > old.length && old.every((o, i) => animEq(o, anims[i]!))) {
    const added = anims.slice(old.length)
    if (added[0]!.trigger !== 'onClick') return null
    // Mixing whole-shape and paragraph animations on one shape changes the bldP form
    // (plain ↔ build="p"); defer to a full rebuild
    const kindBySpid = new Map<number, number>()
    for (const a of anims)
      kindBySpid.set(a.spid, (kindBySpid.get(a.spid) ?? 0) | (a.paragraph == null ? 1 : 2))
    if (added.some((a) => kindBySpid.get(a.spid) === 3)) return null
    const seqM = /<p:cTn\b[^>]*\bnodeType="mainSeq"[^>]*>/.exec(timing)
    if (!seqM) return null
    const childOpen = timing.indexOf('<p:childTnLst>', seqM.index + seqM[0].length)
    if (childOpen < 0) return null
    const childClose = findBalancedClose(timing, childOpen, 'p:childTnLst')
    if (childClose < 0) return null

    const gen = makeGenAfterMaxId(timing)
    const grpBase = new Map<number, number>()
    for (const a of old) grpBase.set(a.spid, (grpBase.get(a.spid) ?? 0) + 1)
    const groups = placeAnims(added, grpBase)
    const groupsXml = groups.map((g) => groupParXml(gen, g)).join('')
    let newTiming = timing.slice(0, childClose) + groupsXml + timing.slice(childClose)
    newTiming = appendBldPs(
      newTiming,
      groups.flatMap((g) => g.items),
    )
    return splice(newTiming)
  }

  // B. Tail single-item edit
  if (anims.length === old.length) {
    const diffIdx = anims.flatMap((a, i) => (animEq(a, old[i]!) ? [] : [i]))
    if (diffIdx.length !== 1) return null
    const i = diffIdx[0]!
    const o = old[i]!
    const a = anims[i]!
    // Trigger/target unchanged (a paragraph change affects the bldP form); no later withPrev/afterPrev chain depends on this item's start/end
    if (o.trigger !== a.trigger || o.spid !== a.spid) return null
    if ((o.paragraph ?? null) !== (a.paragraph ?? null)) return null
    const next = anims[i + 1]
    if (next && next.trigger !== 'onClick') return null
    const span = nthEffectParSpan(timing, i)
    if (!span) return null
    const gen = makeGenAfterMaxId(timing)
    // Keep the original cTn's grpId (bldP is keyed on it); recompute from the list only when missing
    const origGrpId = /\bgrpId="(\d+)"/.exec(timing.slice(span.start, span.end))?.[1]
    const grpId =
      origGrpId != null
        ? Number(origGrpId)
        : anims.slice(0, i).filter((x) => x.spid === a.spid).length
    const par = effectParXml(gen, { a, startMs: absStarts(anims)[i]!, grpId })
    return splice(timing.slice(0, span.start) + par + timing.slice(span.end))
  }

  return null
}

/**
 * Set the slide's full animation list. Tries the incremental patch first (append /
 * tail single-item edit, keeping unmodeled timing nodes); when inapplicable, falls
 * back to the overwrite-style full rebuild (writes bodySuffix, persisted with the
 * whole-slide rebuild on save).
 */
export function setSlideAnimations(slide: Slide, anims: SlideAnimation[]): void {
  slide.bodySuffix =
    patchSlideTimingIncrementalXml(slide.bodySuffix, anims) ??
    patchSlideTimingXml(slide.bodySuffix, anims)
  slide.structureDirty = true
}

/** Read the current slide's animation list. */
export function getSlideAnimations(slide: Slide): SlideAnimation[] {
  return readSlideTimingXml(slide.bodySuffix)
}

/** Innermost balanced <tag>…</tag> span containing the given index. */
function enclosingTagSpan(
  xml: string,
  at: number,
  tag: string,
): { start: number; end: number } | null {
  const re = new RegExp(`<${tag}\\b[^>]*>|</${tag}>`, 'g')
  const stack: number[] = []
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    if (m[0][1] !== '/') {
      if (!m[0].endsWith('/>')) stack.push(m.index)
    } else {
      const start = stack.pop()
      if (start === undefined) return null
      if (start <= at && at < re.lastIndex) return { start, end: re.lastIndex }
    }
  }
  return null
}

/** Nearest preceding open <tag> that is still open at `at` (self-closing and
    already-closed occurrences skipped; these tags do not self-nest). */
function wrappedBy(xml: string, at: number, tag: string): boolean {
  let from = at
  for (;;) {
    const open = xml.lastIndexOf(`<${tag}`, from)
    if (open < 0) return false
    const gt = xml.indexOf('>', open)
    if (gt < 0) return false
    if (xml[gt - 1] === '/') {
      from = open - 1
      continue
    }
    return xml.indexOf(`</${tag}>`, gt) > at
  }
}

/** Whether the spTgt at `at` is a trigger reference (wrapped by an open
    <p:cond>) rather than an effect/media target — an effect block's own
    already-closed delay cond (<p:cond delay="0"/> inside its cTn) must not
    count as a wrapper. */
function isTriggerRef(xml: string, at: number): boolean {
  return wrappedBy(xml, at, 'p:cond')
}

/**
 * Remove the effect blocks targeting the given cNvPr ids from the slide's
 * <p:timing>. Element removal must go through this or the timing keeps
 * dangling <p:spTgt spid> refs (PowerPoint flags the file). Byte surgery —
 * unmodeled effect parameters elsewhere survive (no rebuild):
 * - a trigger reference (<p:cond><p:tgtEl>) takes its whole interactiveSeq
 *   with it (the animations only ever ran off the removed trigger shape);
 * - an effect/media target removes the narrowest wrapper (video/audio/par)
 *   that does not contain surviving shapes' targets — when no such wrapper
 *   exists the ref is left in place rather than destroying other animations;
 * - matching <p:bldP> build refs go too; a timing left with no targets and
 *   no diagram builds is dropped entirely.
 */
export function pruneTimingForSpids(slide: Slide, spids: ReadonlySet<number>): boolean {
  if (!spids.size) return false
  const timing = /<p:timing>[\s\S]*?<\/p:timing>/.exec(slide.bodySuffix)?.[0]
  if (!timing) return false
  let xml = timing
  let changed = false
  for (;;) {
    const hits = [...xml.matchAll(/<p:spTgt spid="(\d+)"/g)].filter((x) => spids.has(Number(x[1])))
    let removed = false
    for (const hit of hits) {
      const at = hit.index
      let span: { start: number; end: number } | null = null
      if (isTriggerRef(xml, at)) {
        const seq = enclosingTagSpan(xml, at, 'p:seq')
        if (seq) {
          const head = xml.slice(seq.start, seq.start + 400)
          if (head.includes('nodeType="interactiveSeq"')) span = seq
        }
      }
      if (!span) {
        const candidates = ['p:video', 'p:audio', 'p:par']
          .map((t) => enclosingTagSpan(xml, at, t))
          .filter((sp): sp is { start: number; end: number } => sp !== null)
          .sort((a, b) => a.end - a.start - (b.end - b.start))
        span =
          candidates.find(
            (sp) =>
              ![...xml.slice(sp.start, sp.end).matchAll(/<p:spTgt spid="(\d+)"/g)].some(
                (m) => !spids.has(Number(m[1])),
              ),
          ) ?? null
      }
      if (!span) continue
      xml = xml.slice(0, span.start) + xml.slice(span.end)
      changed = true
      removed = true
      break
    }
    if (!removed) break
  }
  for (const id of spids) {
    const re = new RegExp(
      `<p:bldP spid="${id}"[^>]*/>|<p:bldP spid="${id}"[^>]*>[\\s\\S]*?</p:bldP>`,
      'g',
    )
    if (re.test(xml)) {
      xml = xml.replace(re, '')
      changed = true
    }
  }
  if (!changed) return false
  xml = xml.replace(/<p:bldLst\s*\/>|<p:bldLst\s*>\s*<\/p:bldLst>/g, '')
  if (/<p:spTgt\b/.test(xml)) {
    // Collapse innermost pars that lost every target, then their emptied ancestors
    let prev: string
    do {
      prev = xml
      xml = xml.replace(/<p:par\b[^>]*>(?:(?!<p:par\b|<\/p:par>)[\s\S])*?<\/p:par>/g, (blk) =>
        /<p:spTgt\b/.test(blk) ? blk : '',
      )
    } while (xml !== prev)
  }
  slide.bodySuffix =
    /<p:spTgt\b/.test(xml) || /<p:bldDgm\b/.test(xml)
      ? slide.bodySuffix.replace(timing, xml)
      : slide.bodySuffix.replace(timing, '')
  slide.structureDirty = true
  return true
}

/** Every cNvPr id inside an element's XML fragment (group children included). */
export function cNvPrIdsInXml(xml: string): Set<number> {
  const out = new Set<number>()
  for (const m of xml.matchAll(/<p:cNvPr\b[^>]*?\bid="(\d+)"/g)) out.add(Number(m[1]))
  return out
}
