/**
 * prstGeom names insertable via the ribbon gallery and the AI add_shape op.
 * Single source for the save-request schema, the AI DSL, and the journal
 * filter; the drawing gateway writes these verbatim into <a:prstGeom prst>.
 */
export const ADDABLE_SHAPE_TYPES = [
  // rectangles
  'rect',
  'roundRect',
  'snip1Rect',
  'snip2SameRect',
  'snip2DiagRect',
  'snipRoundRect',
  'round1Rect',
  'round2SameRect',
  'round2DiagRect',
  // basic shapes
  'ellipse',
  'triangle',
  'rtTriangle',
  'parallelogram',
  'trapezoid',
  'diamond',
  'pentagon',
  'hexagon',
  'octagon',
  'plus',
  'mathPlus',
  'pie',
  'chord',
  'teardrop',
  'frame',
  'halfFrame',
  'corner',
  'diagStripe',
  'donut',
  'noSmoking',
  'blockArc',
  'foldedCorner',
  'bevel',
  'cube',
  'can',
  'lightningBolt',
  'heart',
  'sun',
  'moon',
  'cloud',
  'arc',
  'plaque',
  'smileyFace',
  'leftBracket',
  'rightBracket',
  'leftBrace',
  'rightBrace',
  // block arrows
  'rightArrow',
  'leftArrow',
  'upArrow',
  'downArrow',
  'leftRightArrow',
  'upDownArrow',
  'quadArrow',
  'bentArrow',
  'uturnArrow',
  'curvedRightArrow',
  'stripedRightArrow',
  'notchedRightArrow',
  'chevron',
  'homePlate',
  // stars and banners
  'star4',
  'star5',
  'star6',
  'star7',
  'star8',
  'star10',
  'star12',
  'star16',
  'star24',
  'star32',
  'irregularSeal1',
  'irregularSeal2',
  'ribbon',
  'ribbon2',
  'wave',
  'doubleWave',
  // flowchart
  'flowChartProcess',
  'flowChartAlternateProcess',
  'flowChartDecision',
  'flowChartPredefinedProcess',
  'flowChartInternalStorage',
  'flowChartDocument',
  'flowChartMultidocument',
  'flowChartTerminator',
  'flowChartPreparation',
  'flowChartManualInput',
  'flowChartManualOperation',
  'flowChartConnector',
  'flowChartOffpageConnector',
  'flowChartMagneticDisk',
  'flowChartMagneticDrum',
  'flowChartDisplay',
  'flowChartDelay',
  'flowChartOr',
  'flowChartCollate',
  'flowChartSort',
  'flowChartExtract',
  'flowChartMerge',
  'flowChartSummingJunction',
  'flowChartPunchedTape',
  // callouts
  'wedgeRectCallout',
  'wedgeRoundRectCallout',
  'wedgeEllipseCallout',
  'cloudCallout',
] as const

export type AddableShapeType = (typeof ADDABLE_SHAPE_TYPES)[number]
