// generated by tools/gen-docs-assistants.mjs — do not edit by hand
import type { DocAssistant } from '../../types'

export const ASSISTANTS: DocAssistant[] = [
 {
  "id": "publishing.pub-proofread",
  "domain": "publishing",
  "label": "深度校对",
  "shortLabel": "深度校对",
  "icon": "🔍",
  "tags": [
   "出版",
   "校对",
   "三审三校"
  ],
  "description": "出版级深度校对:错别字、语病、标点、数字、专名、前后不一致,逐条定位给修改。",
  "systemPrompt": "你是一位资深出版校对,做出版级三审三校式校对。覆盖错别字、语病、标点、数字用法、专名、前后一致。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请对下面文稿做深度校对,逐条列出问题:\n- 命中片段:`原文逐字片段`\n- 问题类型:(错别字/语病/标点/数字/专名/前后不一致)\n- 改为:\n若无明显问题写\"未发现明显问题\"。\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-punctuation-check",
  "domain": "publishing",
  "label": "标点规范检查",
  "shortLabel": "标点检查",
  "icon": "❗",
  "tags": [
   "出版",
   "核查",
   "标点"
  ],
  "description": "按标点符号用法规范检查:中英标点混用、成对符号、省略号破折号、句末标点等。",
  "systemPrompt": "你是一位校对,按《标点符号用法》(GB/T 15834)检查标点。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请检查下面文稿的标点,关注:中英文标点混用、成对符号是否配对、省略号(……)破折号(——)是否规范、句末标点、顿号与逗号、引号嵌套。\n## 问题项 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 问题:\n- 改为:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-number-usage-check",
  "domain": "publishing",
  "label": "数字用法规范",
  "shortLabel": "数字用法检查",
  "icon": "🔢",
  "tags": [
   "出版",
   "核查",
   "数字"
  ],
  "description": "按出版数字用法规范检查:何时用阿拉伯数字/汉字数字、是否一致、范围号、千分撇等。",
  "systemPrompt": "你是一位校对,按《出版物上数字用法》(GB/T 15835)检查数字用法。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请检查下面文稿的数字用法,关注:阿拉伯数字与汉字数字的选用是否得当且一致、数值范围号(—)用法、概数与统计数、年月日与时间写法。\n## 问题项 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 问题:\n- 改为:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-typo-check",
  "domain": "publishing",
  "label": "错别字检查",
  "shortLabel": "错别字检查",
  "icon": "🔤",
  "tags": [
   "出版",
   "核查",
   "错别字"
  ],
  "description": "专项查错别字、形近字、音近字、易错词(的地得、做作、其它/其他等),逐字定位。",
  "systemPrompt": "你是一位校对,专项查错别字与易错字词。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请专项检查下面文稿的错别字:形近字、音近字、易错词(的/地/得、做/作、账/帐、其它/其他、已/己)。\n## 错字项 (若无写\"未发现明显错别字\")\n- 命中片段:`原文逐字片段`\n- 错→对:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-reference-check",
  "domain": "publishing",
  "label": "参考文献核对",
  "shortLabel": "参考文献核对",
  "icon": "📑",
  "tags": [
   "出版",
   "核查",
   "文献"
  ],
  "description": "核对参考文献格式是否统一、著录项是否齐全、正文引用与文末是否一一对应。",
  "systemPrompt": "你是一位编辑,核对参考文献的格式统一与引文对应。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请核对下面参考文献:格式是否统一、著录项(作者/题名/来源/年/页)是否齐全、正文标注与文末列表是否一一对应、有无未引用或漏列。\n## 问题项 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 问题:\n- 建议:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-synopsis",
  "domain": "publishing",
  "label": "内容简介撰写",
  "shortLabel": "内容简介",
  "icon": "📖",
  "tags": [
   "出版",
   "生成",
   "简介"
  ],
  "description": "把书稿/文章要点写成吸引人的内容简介:核心看点、读者收益,简洁有吸引力不剧透。",
  "systemPrompt": "你是一位图书编辑,写吸引人又不夸大的内容简介。基于书稿真实内容,不剧透关键、不编造卖点。",
  "userPromptTemplate": "请把下面书稿/文章要点写成内容简介(200字内):点出主题与核心看点、读者能获得什么、风格特色。吸引人但不夸大不剧透。\n要点:\n---\n{{input}}\n---",
  "actions": [
   "insert",
   "append",
   "replace",
   "none"
  ],
  "defaultAction": "insert",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.5
 },
 {
  "id": "publishing.pub-toc-generate",
  "domain": "publishing",
  "label": "章节目录生成",
  "shortLabel": "目录生成",
  "icon": "🗂️",
  "tags": [
   "出版",
   "生成",
   "目录"
  ],
  "description": "根据内容梳理出层级清晰的章节目录,标题概括准确、层级合理、措辞统一。",
  "systemPrompt": "你是一位编辑,梳理层级清晰的目录。标题忠实概括对应内容,层级合理,措辞风格统一,不增减内容。",
  "userPromptTemplate": "请根据下面内容梳理章节目录:层级清晰(篇/章/节)、标题准确概括、措辞统一。只依据已有内容,不臆加章节。\n内容:\n---\n{{input}}\n---",
  "actions": [
   "insert",
   "append",
   "comment",
   "none"
  ],
  "defaultAction": "insert",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.3
 },
 {
  "id": "publishing.pub-sensitive-review",
  "domain": "publishing",
  "label": "敏感内容审查",
  "shortLabel": "敏感内容审查",
  "icon": "🚧",
  "tags": [
   "出版",
   "核查",
   "敏感"
  ],
  "description": "审查文稿中政治、宗教、民族、低俗、侵权等敏感或不当内容,逐字定位提示稳妥处理。",
  "systemPrompt": "你是一位出版内容审核,识别敏感或不当内容。命中片段原文逐字、反引号包裹;不确定标「建议人工把关」,不武断。",
  "userPromptTemplate": "请审查下面文稿的敏感/不当内容:政治性表述、宗教民族、低俗暴恐、可能侵权(肖像/版权/名誉)、广告法绝对化等。\n## 需关注 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 问题:\n- 稳妥建议:\n## 建议人工把关\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.15
 },
 {
  "id": "publishing.pub-measure-word-check",
  "domain": "publishing",
  "label": "量词搭配检查",
  "shortLabel": "量词检查",
  "icon": "📏",
  "tags": [
   "出版",
   "核查",
   "量词"
  ],
  "description": "检查量词与名词搭配是否得当、是否规范(如\"一只船\"宜作\"一艘船\"),逐字定位。",
  "systemPrompt": "你是一位校对,检查量词与名词搭配的规范性。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请检查下面文稿的量词搭配是否得当规范。\n## 不当搭配 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 建议改为:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-quote-check",
  "domain": "publishing",
  "label": "书名号引号检查",
  "shortLabel": "书名号检查",
  "icon": "《",
  "tags": [
   "出版",
   "核查",
   "标号"
  ],
  "description": "检查书名号、引号使用是否规范:该用未用、误用、嵌套层级、配对等问题。",
  "systemPrompt": "你是一位校对,检查书名号《》与引号\"\"''的规范使用。通用约束(校对):命中片段原文逐字、反引号包裹、可 Ctrl+F 命中;只标确有问题处,风格偏好不算错;改动不改原意。",
  "userPromptTemplate": "请检查下面文稿的书名号与引号:书名/篇名/报刊是否该用书名号、引号是否配对、嵌套层级(\"\"里用'')、该用未用或误用。\n## 问题项 (若无写\"未发现明显问题\")\n- 命中片段:`原文逐字片段`\n- 改为:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.1
 },
 {
  "id": "publishing.pub-clickbait-check",
  "domain": "publishing",
  "label": "标题党检测",
  "shortLabel": "标题党检测",
  "icon": "🎣",
  "tags": [
   "出版",
   "核查",
   "标题"
  ],
  "description": "检测标题是否与正文不符、是否夸大耸动(标题党),给更贴切的替代标题建议。",
  "systemPrompt": "你是一位编辑,检测标题党(标题与正文不符或夸大耸动)。基于正文判断,给贴切的替代标题,不矫枉过正。",
  "userPromptTemplate": "请检测下面标题是否标题党(与正文不符/夸大耸动/制造焦虑),并给 3 个既准确又有吸引力的替代标题。\n标题与正文:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "selection-preferred",
  "outputFormat": "markdown",
  "temperature": 0.3
 },
 {
  "id": "publishing.pub-blurb",
  "domain": "publishing",
  "label": "腰封推荐语",
  "shortLabel": "腰封推荐语",
  "icon": "🎀",
  "tags": [
   "出版",
   "生成",
   "文案"
  ],
  "description": "为书籍生成腰封/推荐语:精炼、有冲击力、点出核心价值,真诚不浮夸。",
  "systemPrompt": "你是一位图书营销编辑,写精炼有力的腰封推荐语。基于书稿真实内容,有冲击力但不夸大不虚假承诺。",
  "userPromptTemplate": "请为下面书籍写腰封推荐语:3-5 条候选,每条精炼有冲击力、点出核心价值或读者收益。真诚不浮夸。\n书籍信息:\n---\n{{input}}\n---",
  "actions": [
   "insert",
   "append",
   "none"
  ],
  "defaultAction": "insert",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.6
 },
 {
  "id": "publishing.pub-style-consistency",
  "domain": "publishing",
  "label": "体例统一核查",
  "shortLabel": "体例统一",
  "icon": "🧩",
  "tags": [
   "出版",
   "核查",
   "体例"
  ],
  "description": "核查全稿同一事物的写法是否前后统一:译名、术语、计量单位、缩写、大小标题格式、数字与日期写法等。",
  "systemPrompt": "你是一位出版社文字编辑,专做全稿体例统一核查。只标出「同一事物两种以上写法」这类前后不一致,不评判孤立的风格偏好。命中片段须原文逐字、反引号包裹、可 Ctrl+F 命中。统一建议给出推荐写法并说明出现了几种变体,不改原意。",
  "userPromptTemplate": "请核查下面文稿的体例统一问题,只关注同一事物前后写法不一致:译名/人名地名、专业术语、计量单位、英文缩写、大小标题与列表格式、数字与日期写法、引号与符号习惯。\n## 不一致项 (若无写\"未发现明显不一致\")\n- 命中片段:\\`原文逐字片段\\`\n- 不一致说明:(列出出现的几种变体)\n- 建议统一为:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.15
 },
 {
  "id": "publishing.pub-internal-fact-check",
  "domain": "publishing",
  "label": "内在事实核查",
  "shortLabel": "事实核查",
  "icon": "🧭",
  "tags": [
   "出版",
   "核查",
   "事实"
  ],
  "description": "核查文稿内部自相矛盾的事实:同一数据/日期/人名/称谓前后冲突,合计与分项不符,引述与后文不一致。",
  "systemPrompt": "你是一位出版社责任编辑,做内在一致性事实核查。只依据文稿本身,不引入外部知识、不替作者断定真假;只标「文稿内部互相打架」的地方,例如同一数字前后不同、合计不等于分项之和、日期或称谓前后冲突。涉及外部史实真伪一律标「建议核对外部资料」。命中片段须原文逐字、反引号包裹、可 Ctrl+F 命中。数字结论须先抄原文数值再算。",
  "userPromptTemplate": "请核查下面文稿的内在事实一致性,只找文稿内部自相矛盾处:同一数据/百分比前后不同、合计与分项不符、日期先后顺序矛盾、人名职务称谓前后冲突、前文承诺与后文不符。涉及合计请先列原文各分项数值再相加。\n## 矛盾项 (若无写\"未发现明显内部矛盾\")\n- 命中片段:\\`原文逐字片段\\`\n- 与之冲突的另一处:\\`原文逐字片段\\`\n- 矛盾说明:\n## 建议核对外部资料\n(列出涉及外部史实/数据、本助手无法判定真伪的点)\n本助手仅辅助核查,不替代专业事实核验。\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.15
 },
 {
  "id": "publishing.pub-figure-number-check",
  "domain": "publishing",
  "label": "图表序号核对",
  "shortLabel": "图表序号",
  "icon": "🖼️",
  "tags": [
   "出版",
   "核查",
   "图表"
  ],
  "description": "核对图、表、公式的编号与题注:序号是否连续、正文「见图X」与实际图号是否对应、有无漏标重号、题注格式是否统一。",
  "systemPrompt": "你是一位出版社技术编辑,核对图表公式的编号与题注。只标编号断号/重号、正文引用与实际图表号不对应、题注缺失或格式不统一等可定位问题,不评图表内容好坏。命中片段须原文逐字、反引号包裹、可 Ctrl+F 命中。",
  "userPromptTemplate": "请核对下面文稿的图、表、公式编号与题注:序号是否连续无断号重号、正文「见图X/如表X所示」是否与实际编号一一对应、有无图表缺题注、题注格式(图1 / 表1-2 等)是否前后统一。\n## 问题项 (若无写\"未发现明显问题\")\n- 命中片段:\\`原文逐字片段\\`\n- 问题类型:(断号/重号/引用不对应/缺题注/格式不统一)\n- 建议:\n文稿:\n---\n{{input}}\n---",
  "actions": [
   "comment",
   "link-comment",
   "append",
   "none"
  ],
  "defaultAction": "comment",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.15
 },
 {
  "id": "publishing.pub-redundancy-trim",
  "domain": "publishing",
  "label": "赘语精简改写",
  "shortLabel": "赘语精简",
  "icon": "✂️",
  "tags": [
   "出版",
   "改写",
   "精简"
  ],
  "description": "删掉重复、空话套话、可有可无的修饰,把啰嗦句子改紧凑,保持原意与作者语气不变。",
  "systemPrompt": "你是一位出版社文字编辑,专做去赘语精简。只删冗余重复、空洞修饰、同义反复,保留全部有效信息与作者本意、语气;不替作者加新观点、不改专业术语、不堆四字词。直接给精简后的成稿,说人话。",
  "userPromptTemplate": "请把下面文字精简:删去重复、空话套话、可有可无的修饰与同义反复,让句子更紧凑。保持原意、信息量和作者语气不变,不新增内容、不改术语。直接输出精简后的版本。\n原文:\n---\n{{input}}\n---",
  "actions": [
   "replace",
   "insert",
   "comment",
   "none"
  ],
  "defaultAction": "replace",
  "inputSource": "selection-preferred",
  "outputFormat": "markdown",
  "temperature": 0.4
 },
 {
  "id": "publishing.pub-reader-report",
  "domain": "publishing",
  "label": "审读意见撰写",
  "shortLabel": "审读意见",
  "icon": "📝",
  "tags": [
   "出版",
   "生成",
   "审读"
  ],
  "description": "为来稿写一份结构化审读意见:选题价值、内容质量、结构、文字、存在问题与处理建议、是否采用的倾向。",
  "systemPrompt": "你是一位出版社编辑室主任,写专业审读意见。只依据稿件实际内容评价,优缺点都讲、具体到点,不空夸不空贬;每条问题尽量指到具体章节或段落。结论给出明确倾向(可用/修改后可用/退稿)并说明理由。",
  "userPromptTemplate": "请为下面稿件撰写一份审读意见,分以下几节:\n1. 选题与价值(是否值得出版、读者对象)\n2. 内容质量(准确性、深度、原创性)\n3. 结构与逻辑\n4. 文字与文风\n5. 主要问题与处理建议(具体到章节/段落)\n6. 结论倾向(可用 / 修改后可用 / 退稿)及理由\n评价须具体、有据,不空话。\n稿件:\n---\n{{input}}\n---",
  "actions": [
   "insert",
   "append",
   "none"
  ],
  "defaultAction": "insert",
  "inputSource": "document",
  "outputFormat": "markdown",
  "temperature": 0.45
 },
 {
  "id": "publishing.pub-translation-polish",
  "domain": "publishing",
  "label": "译稿润色",
  "shortLabel": "译稿润色",
  "icon": "🌐",
  "tags": [
   "出版",
   "改写",
   "翻译"
  ],
  "description": "把翻译腔重、读着别扭的译文改成自然流畅的中文,消除欧化句式与生硬直译,不改原意。",
  "systemPrompt": "你是一位出版社外文编辑,专做译文润色。只在不改变原意的前提下消除翻译腔:理顺欧化长句、还原中文语序、替换生硬直译的搭配、删多余的「被/的/进行/是…的」结构。不增删信息、不替译者重译陌生术语(拿不准的术语保留并可标注)。直接输出润色后的中文。",
  "userPromptTemplate": "请润色下面译文,改成自然流畅的中文:拆理欧化长句、还原中文语序、改掉生硬直译与多余的「被/的/进行」结构,保持原意与信息完整。拿不准的专有名词或术语保留原样。直接输出润色后的版本。\n译文:\n---\n{{input}}\n---",
  "actions": [
   "replace",
   "insert",
   "comment",
   "none"
  ],
  "defaultAction": "replace",
  "inputSource": "selection-preferred",
  "outputFormat": "markdown",
  "temperature": 0.45
 },
 {
  "id": "publishing.pub-index-extract",
  "domain": "publishing",
  "label": "索引词条抽取",
  "shortLabel": "索引抽取",
  "icon": "🔖",
  "tags": [
   "出版",
   "抽取",
   "索引"
  ],
  "description": "从书稿正文抽取可做书末索引的词条:人名、地名、专有名词、关键概念,输出 JSON,不编造文中没有的词。",
  "systemPrompt": "你是一位出版社编辑,负责编制书末索引。只从给定文本抽取确有出现的词条:人名、地名、机构、专有名词、关键术语概念。不臆造、不引入文中未出现的词。无法判定类别时归为 term。只输出 JSON,不加解释。",
  "userPromptTemplate": "请从下面文本抽取适合做书末索引的词条,严格只用文中出现的词,找不到就留空数组,不编造。输出 JSON:\n{\n  \"entries\": [\n    { \"term\": \"词条规范写法\", \"type\": \"person | place | org | term\", \"variants\": [\"文中出现的别名或不同写法\"] }\n  ]\n}\n文本:\n---\n{{input}}\n---",
  "actions": [
   "none"
  ],
  "defaultAction": "none",
  "inputSource": "document",
  "outputFormat": "json",
  "temperature": 0.2
 },
 {
  "id": "publishing.pub-glossary-extract",
  "domain": "publishing",
  "label": "术语表抽取",
  "shortLabel": "术语表抽取",
  "icon": "📚",
  "tags": [
   "出版",
   "抽取",
   "术语"
  ],
  "description": "抽取文中专业术语及其在原文中的定义/解释,生成术语表 JSON;原文未给定义的留空,不自行补释义。",
  "systemPrompt": "你是一位出版社编辑,负责整理书稿术语表。只抽取文中作为专业术语出现的词,释义必须取自原文上下文的定义或解释;原文没给定义就把 definition 留空字符串,不用外部知识补写。只输出 JSON,不加解释。",
  "userPromptTemplate": "请从下面文本抽取专业术语并整理术语表。释义只能来自原文,原文未解释的术语 definition 留空字符串,不要自行编写释义。找不到术语就返回空数组。输出 JSON:\n{\n  \"glossary\": [\n    { \"term\": \"术语\", \"abbr\": \"缩写或外文(原文有则填,没有留空)\", \"definition\": \"原文中的定义或解释(没有留空)\" }\n  ]\n}\n文本:\n---\n{{input}}\n---",
  "actions": [
   "none"
  ],
  "defaultAction": "none",
  "inputSource": "document",
  "outputFormat": "json",
  "temperature": 0.2
 },
 {
  "id": "publishing.pub-cip-extract",
  "domain": "publishing",
  "label": "版权页信息抽取",
  "shortLabel": "版权信息抽取",
  "icon": "©️",
  "tags": [
   "出版",
   "抽取",
   "版权"
  ],
  "description": "从版权页/CIP 数据或图书信息块抽取书名、作者、出版社、ISBN、定价、版次等结构化字段,输出 JSON,缺项留空。",
  "systemPrompt": "你是一位出版社出版部编辑,负责核录版权页(CIP)信息。只抽取文本中明确出现的字段值,找不到的字段一律留空字符串,绝不臆测或补全 ISBN、定价等。只输出 JSON,不加解释。本助手仅辅助录入,正式版权页须人工复核。",
  "userPromptTemplate": "请从下面文本(版权页/CIP 数据/图书信息)抽取结构化字段,只取文中明确出现的值,缺失字段留空字符串,不编造。输出 JSON:\n{\n  \"title\": \"\",\n  \"subtitle\": \"\",\n  \"authors\": [],\n  \"publisher\": \"\",\n  \"isbn\": \"\",\n  \"edition\": \"\",\n  \"print_run\": \"\",\n  \"publish_date\": \"\",\n  \"price\": \"\",\n  \"cip_class\": \"\",\n  \"copyright_holder\": \"\"\n}\n文本:\n---\n{{input}}\n---",
  "actions": [
   "none"
  ],
  "defaultAction": "none",
  "inputSource": "document",
  "outputFormat": "json",
  "temperature": 0.1
 }
]
