import type { Editor } from '@tiptap/core'
import type { RibbonFormatState } from '../../src/renderer/components/ribbon-format-state'

const noop = () => {}

/** Every Ribbon prop, so a test can mount the real component and drive one control. */
export function ribbonProps(editor: Editor, formatState: RibbonFormatState) {
  return {
    editor,
    formatState,
    hasDoc: true,
    blocks: [],
    onOpen: noop,
    onSave: noop,
    onSaveAs: noop,
    showAi: false,
    onToggleAi: noop,
    section: null,
    onSection: noop,
    activeSection: null,
    onInsertSectionBreak: noop,
    pageColor: null,
    onPageColor: noop,
    watermark: null,
    onWatermark: noop,
    themeFonts: null,
    onThemeFonts: noop,
    themeColors: null,
    onThemeColors: noop,
    inkTool: 'select' as const,
    onInkTool: noop,
    inkPen: { color: 'C00000', width: 2 },
    onInkPen: noop,
    inkHighlighter: { color: 'FFFF00', width: 10 },
    onInkHighlighter: noop,
    inkCount: 0,
    onInkClearAll: noop,
    onInsertNote: noop,
    sources: [],
    onAddSource: noop,
    zoom: 100,
    onZoom: noop,
    onZoomFit: noop,
    darkPage: false,
    onDarkPage: noop,
    onAiPreset: noop,
    header: null,
    onHeader: noop,
    onPageNumFormat: noop,
    onInsertField: noop,
    footer: null,
    onFooter: noop,
    titlePg: false,
    onTitlePg: noop,
    evenOddHf: false,
    onEvenOddHf: noop,
    showMarks: false,
    onShowMarks: noop,
    showRuler: false,
    onShowRuler: noop,
    showNav: false,
    onShowNav: noop,
    commentCount: 0,
    openCommentCount: 0,
    onShowComments: noop,
    canComment: false,
    onNewComment: noop,
    trackChanges: false,
    onTrackChanges: noop,
    spellcheck: true,
    onSpellcheck: noop,
    revisionDisplay: 'all' as const,
    onRevisionDisplay: noop,
    revisionCount: 0,
    onAcceptRevision: noop,
    onRejectRevision: noop,
    onGotoRevision: noop,
    isProtected: false,
    commentsAllowed: false,
    trackChangesForced: false,
    protectActive: false,
    onProtectDoc: noop,
    onCompare: noop,
    filePath: null,
    viewMode: 'print' as const,
    onViewMode: noop,
    readMode: false,
    onReadMode: noop,
    showGrid: false,
    onShowGrid: noop,
    splitView: false,
    onSplitView: noop,
    onPagePreview: noop,
  }
}
