/**
 * Build the chatoffice dsh plugin (对齐 chatop-kb/scripts/build.mjs):
 *   1. host 半 src/host.js → dist/host.js（esm, platform=node, bundle 全部
 *      运行时依赖 —— link 安装不装 dependencies，插件必须零 npm 运行依赖）。
 *   2. client 半 src/client-entry.jsx → dist/client.js（__ModuleLoader__
 *      交付格式，React 由内核 require 共享）。
 */
import { build } from 'esbuild'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')
mkdirSync(dist, { recursive: true })

// ── host ────────────────────────────────────────────────────────────────────
await build({
  entryPoints: [join(root, 'src', 'host.js')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  minify: true,
  outfile: join(dist, 'host.js'),
})
console.log(`host: ${readFileSync(join(dist, 'host.js')).byteLength} bytes`)

// ── client ──────────────────────────────────────────────────────────────────
const result = await build({
  entryPoints: [join(root, 'src', 'client-entry.jsx')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  write: false,
  external: ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/client'],
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.js': 'jsx', '.jsx': 'jsx' },
  outdir: 'out',
})
const cjsBody = result.outputFiles[0].text
writeFileSync(
  join(dist, 'client.js'),
  `/** chatoffice client — generated by scripts/build.mjs (esbuild). */\n` +
  `window.__ModuleLoader__.load({\n` +
  `\tid: "chatoffice",\n` +
  `\tfactory: (require) => {\n` +
  `\t\tconst module = { exports: {} };\n` +
  `\t\tconst exports = module.exports;\n` +
  `\t\t${cjsBody.replace(/\n/g, '\n\t\t')}\n` +
  `\t\treturn module.exports;\n` +
  `\t}\n` +
  `});\n`,
)
console.log(`client: ${readFileSync(join(dist, 'client.js')).byteLength} bytes`)
